// Template generated by Clank
#include<bits/stdc++.h>
using namespace std;
#define st first
#define nd second
#define all(x) x.begin(), x.end()
#define BOOST cin.tie(NULL); ios_base::sync_with_stdio(false);
// #define int ll
typedef long long ll;

ll mod = 1e9 + 7;
int n, q;
vector<pair<ll, ll>> events;
vector<ll> sum;
vector<ll> prod;
vector<ll> next_prod_eqm2;
vector<ll> weird_sum;

ll ssum(ll l, ll r, int app_mod=1){
    if(l > r) return 0;
    if(app_mod){
        return (mod + sum[r] - sum[l - 1]) % mod;
    } else {
        return sum[r] - sum[l - 1];
    }
}

// ll fastpow(ll a, ll k){
//     if(k == 0) return 1;
//     ll tmp = fastpow(a, k/2);
//     if(k&1) return (((tmp * tmp) % mod) * a) % mod;
//     else return (tmp * tmp) % mod;
// }

ll fastpow(ll a, ll k){
    ll res = 1;
    while(k > 0){
        if(k & 1) res = (res * a) % mod;
        a = (a * a) % mod;
        k >>= 1;
    }
    return res;
}


ll rev(ll x){
    return fastpow(x, mod - 2);
}

ll sprod(ll l, ll r){
    if(r < l) return 1;
    return (prod[r] * rev(prod[l - 1])) % mod;
}

void solve(){
    ll x, l, r;
    cin >> x >> l >> r;
    // l++;
    // r++;

    ll plus_jump;
    while(x <= mod && l < r){
        plus_jump = min(r, next_prod_eqm2[l]);
        x += ssum(l + 1, plus_jump - 1, 0);
        l = plus_jump;
        if(x > mod){
            l--;
            break;
        }
        if(x + events[l].st > x * events[l].nd){
            x += events[l].st;
        } else {
            x *= events[l].nd;
        }
    }
    // cout << x << "\n";
    // cout << l << " " << r << "\n";
    x %= mod;
    if(l == r){
        cout << x << "\n";
        return;
    }
    // cout << sprod(l + 1, r) << "\n";
    ll ans = (x * sprod(l + 1, r)) % mod;
    // cout << ans << "\n";
    ll ans2 = (weird_sum[l + 1] - weird_sum[r + 1] + mod) % mod;
    // cout << ans2 << "\n";
    ans2 = (ans2 * rev(sprod(r + 1, n))) % mod;
    // cout << ans2 << "\n";
    ans = (ans + ans2) % mod;
    cout << ans << "\n";
    return;
}

int32_t main(){
    // cout << fastpow(2,10) << " " << rev(2546234) << " test\n";
    BOOST;
    cin >> n >> q;
    events.resize(n + 2);
    sum.resize(n + 2);
    prod.resize(n + 2);
    next_prod_eqm2.resize(n + 2);
    weird_sum.resize(n + 2);

    prod[0] = 1;
    for(int i = 1; i <= n; i++){
        cin >> events[i].st >> events[i].nd;
        sum[i] = sum[i - 1] + events[i].st;
        prod[i] = (prod[i - 1] * max(events[i].nd, 1LL)) % mod;    
    }

    int last = n + 1;
    for(int i = n + 1; i >= 0; i--){
        next_prod_eqm2[i] = last;
        if(events[i].nd > 1) last = i;
    }

    ll multi = 1;
    for(int i = n; i >= 0; i--){
        weird_sum[i] = weird_sum[i + 1];
        if(events[i].nd > 1){
            multi = (multi * events[i].nd) % mod;
        } else {
            weird_sum[i] = (weird_sum[i] + events[i].st * multi) % mod;
        }
    }

    while(q--){
        solve();
    }
    return 0;
}
