// Template generated by Clank
#include<bits/stdc++.h>
using namespace std;
#define st first
#define nd second
#define all(x) x.begin(), x.end()
#define BOOST cin.tie(NULL); ios_base::sync_with_stdio(false);
// #define int ll
typedef long long ll;


int32_t main(){
    BOOST;
    int k; cin >> k;
    vector<vector<int>> m(k + 1);
    vector<vector<int>> req(k + 1);
    
    int n;
    cin >> n;
    m[1].assign(n + 1, 0);
    req[0].assign(10, 0);
    req[1].assign(n + 1, 0);
    for(int i = 2; i <= k; i++){
        cin >> n;
        m[i].resize(n + 1);
        req[i].resize(n + 1);
        for(int j = 1; j <= n; j++){
            cin >> m[i][j];
        }
    }
    
    int ans = 0;
    int tans;
    for(int i = k; i > 0; i--){
        tans = 0;
        for(int j = 1; j < (int)req[i].size(); j++){
            if(req[i][j] == 0) req[i][j] = 1;
            tans += req[i][j];
            req[i - 1][m[i][j]] += req[i][j];
        }
        // for(int j : req[i]){
        //     cout << j << " ";
        // }
        // cout << "\n";
        // cout << i << " " << tans << "\n";
        ans = max(ans, tans);
    }
    cout << ans << "\n";
    return 0;
}
