// Template generated by Clank
#include<bits/stdc++.h>
using namespace std;
#define st first
#define nd second
#define all(x) x.begin(), x.end()
#define BOOST cin.tie(NULL); ios_base::sync_with_stdio(false);
// #define int ll
typedef long long ll;

char i2c[]={'P','K','N'};
int c2i[300];
vector<vector<int>> i2s={{1},{0,1},{0,0}};
map<vector<int>, int> s2i;

int jump[]={1,2,2};

int play(int weapon_idx){
    cout << i2c[weapon_idx] << "\n";
    cout.flush();
    char response; cin >> response;
    return c2i[(int)response];
}

void answer(int n, vector<int> &ans){
    cout << "! ";
    for(int i = 0; i < n; i++)
        cout << ans[i];
    cout << "\n";
    cout.flush();
}

int RA(){
    if(RAND_MAX & 1)
        return rand() % 2;
    int tmp = rand();
    while(tmp == RAND_MAX) tmp = rand();
    return tmp % 2;
}

void get_mask(int n, vector<int> &mask){
    mask.resize(n);
    for(int i = 0; i < n; i++){
        mask[i] = RA();
    }
}

int handle_first(vector<int> &s){
    int mmove = s[0];
    int oppmove = play(mmove);
    if(mmove != oppmove){
        play(mmove ^ 1);
    }
    return oppmove;
}

int choose_my_move(int idx, vector<int> &s){
    return s2i[{s[idx - 1] ^ s[idx], s[idx - 1] ^ s[idx + 1]}];
}

void apply_opp_move(int oppmove, int idx, vector<int> &os, vector<int> &oppm){
    for(int i = 0; i < jump[oppmove]; i++){
        os[idx + i] ^= i2s[oppmove][i] ^ (os[idx - 1] ^ oppm[idx - 1]);
    }
}

void gameplay(int n, vector<int> &mym, vector<int> oppm){
    vector<int> s(n + 1, 0), os(n + 1, 0);
    char tmpc;
    for(int i = 0; i < n; i++){
        cin >> tmpc;
        s[i] = (tmpc - '0') ^ mym[i];
        os[i] = oppm[i];
    }
    os[0] ^= handle_first(s);
    // balance = 0;
    int midx = 1;
    int oppidx = 1;
    int mymove, oppmove;
    while(midx < n && oppidx < n){
        mymove = choose_my_move(midx, s);
        oppmove = play(mymove);
        if(mymove != oppmove)
            play(oppmove);
        apply_opp_move(oppmove, oppidx, os, oppm);
        oppidx += jump[oppmove];
        midx += jump[mymove];
    }
    while(midx < n){
        mymove = choose_my_move(midx, s);
        oppmove = play(mymove);
        if(mymove != oppmove)
            play(oppmove);
        midx += jump[mymove];
    }
    while(oppidx < n){
        mymove = 0;
        oppmove = play(mymove);
        if(mymove != oppmove)
            play(oppmove);
        apply_opp_move(oppmove, oppidx, os, oppm);
        oppidx += jump[oppmove];
    }

    answer(n, os);
}

int32_t main(){
    BOOST;
    srand(37488237);
    c2i['P'] = 0;
    c2i['K'] = 1;
    c2i['N'] = 2;
    
    s2i[{1,0}] = 0;
    s2i[{1,1}] = 0;
    s2i[{0,1}] = 1;
    s2i[{0,0}] = 2;

    int n, q;
    string player; cin >> player;    
    cin >> n >> q;
    vector<int> m1, m2;
    while(q--){
        get_mask(n, m1);
        get_mask(n, m2);
        if(player == "Algosia"){
            gameplay(n, m1, m2);
        } else {
            gameplay(n, m2, m1);
        }
    }
    // if(player == "Algosia"){
    //     cin >> n >> q;
    //     while(q--){
    //         Algosia(n);
    //     }
    // } else {
    //     cin >> n >> q;
    //     while(q--){
    //         Bajtek(n);
    //     }
    // }
    return 0;
}
