// Template generated by Clank
#include<bits/stdc++.h>
using namespace std;
#define st first
#define nd second
#define all(x) x.begin(), x.end()
#define BOOST cin.tie(NULL); ios_base::sync_with_stdio(false);
// #define int ll
typedef long long ll;

int n, m, k;
vector<vector<ll>> pinc;
vector<ll> sumv;
vector<ll> presum;

vector<int> order;
vector<ll> padd;
vector<ll> prepadd;

ll ans = 0;
ll lim = 1e12; // 1e12 + 1

bool cmp(int idxa, int idxb){
    return sumv[idxa] >= sumv[idxb];
}

ll sumk(int idx, int cidx){
    if(idx == 0) return 0;
    if(idx - 1 >= cidx)
        return presum[idx] - sumv[order[cidx]];
    else 
        return presum[idx - 1];
}

ll sumpaddk(int idx){
    if(prepadd.size() == 0) return 0;
    if(idx >= (int)prepadd.size()) idx = (int)prepadd.size() - 1;
    return prepadd[idx];
}

ll last_inc(int idx, int cidx){
    if(idx == 0) return lim;
    if(idx - 1 >= cidx) idx++;
    return sumv[order[idx - 1]];
}

ll next_m_dec(int k_left, int ninc){
    return sumpaddk(k_left - ninc * m + m) - sumpaddk(k_left - ninc * m);
}

ll best_option(int k_left, int cidx){
    if(k_left == 0) return 0;
    int l = 0, r = min(k_left / m, max(0, (int)pinc.size() - 1)), mid;
    if(r == 0) return 0;
    if(last_inc(r, cidx) >= next_m_dec(k_left, r)) return sumk(r, cidx) + sumpaddk(k_left - r * m);
    
    while(l + 1 < r){
        mid = (l + r) / 2;
        if(last_inc(mid, cidx) >= next_m_dec(k_left, mid)){
            l = mid;
        } else {
            r = mid;
        }
    }
    return sumk(l, cidx) + sumpaddk(k_left - l * m); 
}

int32_t main(){
    BOOST;
    lim++;
    cin >> n >> m >> k;
    vector<ll> tmpv(m);
    padd.push_back(0);
    int dec = 1;
    ll sum;
    for(int i = 0; i < n; i++){
        sum = 0;
        dec = 1;
        for(int j = 0; j < m; j++){
            cin >> tmpv[j];
            sum += tmpv[j];
            if(tmpv[max(0, j - 1)] < tmpv[j]) dec = 0;
        }
        if(dec){
            for(ll j : tmpv){
                padd.push_back(j);
            }
        } else {
            sumv.push_back(sum);
            pinc.push_back(tmpv);
        }
    }
    sort(1 + all(padd), greater<ll>());
    prepadd.assign(padd.size(), 0);
    for(int i = 1; i < (int)prepadd.size(); i++){
        prepadd[i] = prepadd[i - 1] + padd[i];
    }
    ans = prepadd[min(k, (int)prepadd.size() - 1)];
    
    int npinc = (int)pinc.size();
    if(npinc == 0){
        cout << ans << "\n";
        return 0;
    }
    
    order.resize(npinc);
    iota(all(order), 0);
    sort(all(order), cmp);

    presum.resize(npinc);
    presum[0] = sumv[order[0]];
    for(int i = 1; i < npinc; i++){
        int tidx = order[i];
        presum[i] = presum[i - 1] + sumv[tidx];
    }
    ll tans;
    for(int i = 0; i < npinc; i++){
        int pidx = order[i];
        tans = 0;
        for(int j = 0; j < m; j++){
            if(j + 1 > k) break;
            tans += pinc[pidx][j];
            ll tmp1 = best_option(k - j - 1, i);
            ans = max({ans, tans + tmp1, tans + sumpaddk(k - j - 1)});
        }
    }
    cout << ans << "\n";
    return 0;
}