// Template generated by Clank
#include<bits/stdc++.h>
using namespace std;
#define st first
#define nd second
#define all(x) x.begin(), x.end()
#define BOOST cin.tie(NULL); ios_base::sync_with_stdio(false);
// #define int ll
typedef long long ll;

int n, m, k;
vector<vector<ll>> pinc;
vector<ll> sumv;
vector<ll> presum;

vector<ll> lastv;
vector<ll> prelast;
vector<ll> preseclast;
vector<int> order;
// vector<vector<ll>> pdec;
// vector<ll> sum;
// vector<ll> last
vector<ll> padd;
vector<ll> prepadd;

ll ans = 0;
ll lim = 1e12; // 1e12 + 1

bool cmp(int idxa, int idxb){
    return sumv[idxa] >= sumv[idxb];
}

ll sumk(int idx, int cidx){
    if(idx == 0) return 0;
    if(idx - 1 >= cidx) idx++;
    return presum[idx - 1] - sumv[order[cidx]];
}

ll sumpaddk(int idx){
    if(prepadd.size() == 0) return 0;
    if(idx >= (int)prepadd.size()) idx = (int)prepadd.size() - 1;
    return prepadd[idx];
}

ll nextpadd(int idx){
    idx++;
    if(idx >= (int)padd.size()) return 0;
    return padd[idx];
}

ll minmaxk(int idx, int cidx){
    if(idx == 0) return lim;
    if(idx - 1 >= cidx){
        if(lastv[order[cidx]] == prelast[idx]){
            return preseclast[idx];
        } else {
            return prelast[idx];
        }
    } else {
        return prelast[idx - 1];
    }
}

ll best_option(int k_left, int cidx){
    if(k_left == 0) return 0;
    // int rest = k_left % m;
    int l = 0, r = min(k_left / m, max(0, (int)pinc.size() - 1)), mid;
    if(minmaxk(r, cidx) >= nextpadd(k_left - r * m)) return sumk(r, cidx) + sumpaddk(k_left - r * m);
    
    while(l + 1 < r){
        mid = (l + r) / 2;
        if(minmaxk(mid, cidx) >= nextpadd(k_left - mid * m)){
            l = mid;
        } else {
            r = mid;
        }
    }
    cout << "BO: " << k_left << " " << cidx << " " << l << " " << k_left - l * m << "\n";
    return sumk(l, cidx) + sumpaddk(k_left - l * m); 
}

int32_t main(){
    BOOST;
    lim++;
    cin >> n >> m >> k;
    cout << n << " " << m << " " << k << "\n";
    vector<ll> tmpv(m);
    padd.push_back(0);
    int dec = 1;
    ll sum;
    // sumv.resize(n);
    // lastv.resize(n);
    // order.resize(n);
    for(int i = 0; i < n; i++){
        sum = 0;
        dec = 1;
        for(int j = 0; j < m; j++){
            cin >> tmpv[j];
            cout << tmpv[j] << " ";
            sum += tmpv[j];
            if(tmpv[max(0, j - 1)] < tmpv[j]) dec = 0;
        }
        cout << "\n";
        if(dec){
            // pdec.push_back(tmpv);
            for(ll j : tmpv){
                padd.push_back(j);
            }
        } else {
            // sumv[pinc.size()] = sum;
            // lastv[pinc.size()] = tmpv.back();
            sumv.push_back(sum);
            lastv.push_back(tmpv.back());
            pinc.push_back(tmpv);
        }
    }
    sort(1 + all(padd), greater<ll>());
    prepadd.assign(padd.size(), 0);
    for(int i = 1; i < (int)prepadd.size(); i++){
        prepadd[i] = prepadd[i - 1] + padd[i];
    }
    ans = prepadd[min(k, (int)prepadd.size() - 1)];
    
    int npinc = (int)pinc.size();
    if(npinc == 0){
        cout << ans << "\n";
        return 0;
    }
    
    order.resize(npinc);
    iota(all(order), 0);
    sort(all(order), cmp);

    // for(int i = 0; i < order.size(); i++){
    //     cout << order[i] << " " << sumv[order[i]] << "\n";
    // }

    presum.resize(npinc);
    prelast.resize(npinc);
    preseclast.resize(npinc);
    presum[0] = sumv[order[0]];
    prelast[0] = lastv[order[0]];
    preseclast[0] = lim;
    for(int i = 1; i < npinc; i++){
        int tidx = order[i];
        presum[i] = presum[i - 1] + sumv[tidx];
        
        ll tmp = lastv[tidx];
        prelast[i] = prelast[i - 1];
        preseclast[i] = preseclast[i - 1];
        if(prelast[i] > tmp) swap(prelast[i], tmp);
        if(preseclast[i] > tmp) swap(preseclast[i], tmp);
    }

    cout << "\n";
    for(int i = 0; i < npinc; i++){
        for(int j = 0; j < m; j++){
            cout << pinc[order[i]][j] << " ";
        }
        cout << "\n";
    }
    cout << "\npadd\n";
    for(ll i : padd){
        cout << i << " ";
    }
    cout << "\nprepadd\n";
    for(ll i : prepadd){
        cout << i << " ";
    }

    cout << "\n\nsumv\n";
    for(ll i : order){
        cout << sumv[i] << " ";
    }
    cout << "\nlastv\n";
    for(ll i : order){
        cout << lastv[i] << " ";
    }
    cout << "\npresum\n";
    for(ll i : presum){
        cout << i << " ";
    }
    cout << "\nprelast\n";
    for(ll i : prelast){
        cout << i << " ";
    }
    cout << "\npreseclast\n";
    for(ll i : preseclast){
        cout << i << " ";
    }


    cout << "\n\n" << ans << "\n";


    ll tans;
    for(int i = 0; i < npinc; i++){
        int pidx = order[i];
        tans = 0;
        for(int j = 0; j < m; j++){
            if(j + 1 > k) break;
            tans += pinc[pidx][j];
            ll tmp1 = best_option(k - j - 1, i);
            ans = max({ans, tans + tmp1, tans + sumpaddk(k - j - 1)});
            cout << i << " " << j << " " << tans << " " << tans + tmp1 << " " << tans + sumpaddk(k - j - 1) << " " << ans << "\n";
        }
    }
    cout << ans << "\n";
    return 0;
}
// 171