// Template generated by Clank
#include<bits/stdc++.h>
using namespace std;
#define st first
#define nd second
#define all(x) x.begin(), x.end()
#define BOOST cin.tie(NULL); ios_base::sync_with_stdio(false);
// #define int ll
typedef long long ll;

int n,m,k;
ll ans = 0;
ll mod = 1e9 + 7;
ll revk;
// map<pair<int,vector<int>>, int> states; // ppb na uzyskanie key.nd w key.st rzutach
map<vector<int>, pair<int, ll>> states; // ppb na uzyskanie key.nd w key.st rzutach
set<vector<int>> q;

ll fastpow(ll a, ll k){
    ll res = 1;
    while(k > 0){
        if(k & 1) res = (res * a) % mod;
        a = (a * a) % mod;
        k >>= 1;
    }
    return res;
}
ll rev(ll x){
    return fastpow(x, mod - 2);
}

void generate_moves(vector<int> cs){
    states[cs].st = (rev(states[cs].nd) * states[cs].st) % mod;
    int mini = 1e9, maxi = 0;
    int ctr = 0;
    for(int i = 0; i < cs.size(); i++){
        maxi = max(maxi, cs[i]);
        if(mini >= cs[i]){
            if(mini > cs[i]){
                mini = cs[i];
                ctr = 0;
            }
            ctr++;
        }
    }
    if(maxi >= m){
        ans = (ans + states[cs].st) % mod; 
        return;
    }
    int e = states[cs].st;
    ll poss = states[cs].nd;
    for(int i = 0; i < cs.size(); i++){
        if(cs[i] == mini){
            // ll ppb = (((e[cs] * revk) % mod) * rev(ctr)) % mod;
            for(int j = 1; j <= k; j++){
                cs[i] += j;
                states[cs].nd += poss;
                states[cs].st = (states[cs].st + (e + 1) * poss) % mod;
                q.insert(cs);
                cs[i] -= j;
            }
        }
    }
}

int32_t main(){
    // BOOST;
    cin >> n >> k >> m;
    revk = rev(k);
    vector<int> tmpv(n, 0);
    // pair<int, vector<int>> cs = {0, tmpv};
    states[tmpv] = {0, 1};
    q.insert(tmpv);
    while(!q.empty()){
        auto it = q.begin();
        tmpv = (*it);
        q.erase(it);
        for(int i : tmpv){
            cout << i << " ";
        }
        cout << endl;
        generate_moves(tmpv);
    }
    cout << ans << "\n";
    return 0;
}
