// Template generated by Clank
#include<bits/stdc++.h>
using namespace std;
#define st first
#define nd second
#define all(x) x.begin(), x.end()
#define BOOST cin.tie(NULL); ios_base::sync_with_stdio(false);
// #define int ll
typedef long long ll;

struct node {
    map<int, vector<int>> ce;   // kolor -> vector sasiadow o takim kolorze
    set<pair<int,int>> e;       // vector sasiadow (idx, col[idx])
}

void dfs(int idx, int contr_col, vector<int> &mstack, vector<int> &vis, vector<set<int>> &g, vector<int> &col){
    vis[idx] = 1;
    mstack.push_back(idx);
    for(auto i : g[idx]){
        if(vis[i] || col[i] != contr_col) continue;
        dfs(i, contr_col, mstack, vis, g, col);
    }
}

void contract_v(int v, int u, vector<set<int>> &g){
    for(int i : g[u]){
        if(i == v) continue;
        g[v].insert(i);
        g[i].erase(u);
        g[i].insert(v);
    }
    if(g[v].count(u)) g[v].erase(u);
    // g[u].erase(v);
}

int contract_cc(int sidx, int contr_col, vector<int> &vis, vector<set<int>> &g, vector<int> &col){
    vector<int> to_contract;
    dfs(sidx, contr_col, to_contract, vis, g, col);
    int best_v = -1;
    int max_deg = -1, tdeg;
    for(int v : to_contract){
        tdeg = 0;
        for(int j : g[v]){
            if(col[v] != col[j]) tdeg++;
        }
        if(tdeg > max_deg){
            max_deg = tdeg;
            best_v = v;
        }
    }
    for(int i : to_contract){
        if(i == best_v) continue;
        contract_v(best_v, i, g);
    }
    return best_v;
}

void kill_v(int idx, vector<set<int>> &g, vector<int> &col, vector<map<int,int>> &dead, vector<set<int>> &dead_friend){
    for(int i : g[idx]){
        if(dead[idx].count(col[i])){

        }
    }
}

void print_status(vector<set<int>> &col_alive, vector<set<int>> &g){
    for(int i = 1; i < col_alive.size(); i++){
        cout << "COLOR: " << i << ": ";
        for(int v : col_alive[i]){
            cout << v << " ";
        }
        cout << "\n";
        for(int v : col_alive[i]){
            cout << "edges " << v << ": ";
            for(int u : g[v]){
                cout << u << " ";
            }
            cout << "\n";
        }
    }
}

void solve(){
    int n, m, k;
    cin >> n >> m >> k;
    vector<set<int>> g(2 * n + 2);
    vector<int> col(2 * n + 2, 0);
    for(int i = 1; i <= n; i++){
        cin >> col[i];
    }
    for(int i = 0; i < m; i++){
        int u,v;
        cin >> u >> v;
        g[u].insert(v);
        g[v].insert(u);
    }

    vector<set<int>> col_alive(k + 1);
    vector<int> contracted(n + 1, 0);
    for(int i = 1; i <= n; i++){
        if(!contracted[i]){
            col_alive[col[i]].insert(contract_cc(i, col[i], contracted, g, col));
        }
    }
    queue<int> to_del;
    for(int i = 1; i <= k; i++){
        if(col_alive[i].size() == 1){
            to_del.push(i);
        }
    }
    vector<map<int,int>> dead(2 * n + 2);
    vector<set<int>> dead_friend(n + 1);
    while(!to_del.empty()){
        int v = col[to_del.front()];
        to_del.pop();
        col_alive[col[v]].erase(v);

        kill_v(v, g, col, dead, dead_friend);
        // contract with v + n
        // contract with dead_friends
    }
    for(int i = 1; i <= k; i++){
        if(col_alive[i].size() > 1){
            cout << "NIE\n";
            return;
        }
    }
    cout << "TAK\n";
    return;
}

int32_t main(){
    BOOST;
    int t_; cin >> t_;
    while(t_--){
        solve();
    }
    return 0;
}
