// Template generated by Clank
#include<bits/stdc++.h>
using namespace std;
#define st first
#define nd second
#define all(x) x.begin(), x.end()
#define BOOST cin.tie(NULL); ios_base::sync_with_stdio(false);
// #define int ll
typedef long long ll;

int n;
int logc = 15;
vector<vector<int>> jumps;
vector<vector<int>> g;
vector<int> p;
vector<int> dep;
vector<vector<pair<int,int>>> spath;

/*Binary lifting wziety z biblioteczki*/
void binary_lift(){
    for(int i = 1; i <= n; i++){
        jumps[i][0] = p[i];
    }
    for(int j = 1; j < logc; j++){
        for(int i = 1; i <= n; i++){
            jumps[i][j] = jumps[jumps[i][j - 1]][j - 1];
        }
    }
}
int lca(int x, int y){
    if(dep[x] < dep[y]) swap(x,y);
    for(int i = logc - 1; i >= 0; i--){
        if(dep[jumps[x][i]] >= dep[y]){
            x = jumps[x][i];
        }
    }
    if(x == y){
        return x;
    }
    for(int i = logc - 1; i >= 0; i--){
        if(jumps[x][i] != jumps[y][i]){
            x = jumps[x][i];
            y = jumps[y][i];
        }
    }
    return p[x];
}

void dfs(int idx, int par){
    dep[idx] = dep[par] + 1;
    p[idx] = par;
    for(int i : g[idx]){
        if(i == par) continue;
        dfs(i, idx);
    }
}

int path_len(int u, int v){
    return dep[u] + dep[v] - 2 * dep[lca(u,v)];
}

bool cross(pair<int, int> p1, pair<int,int> p2){
    int lca1 = lca(p1.st, p1.nd);
    int lca2 = lca(p2.st, p2.nd);
    
}

void solve(){
    ll a, b, c; cin >> a >> b >> c;
    if(c > n || spath[a].size() == 0 || spath[b].size() == 0 || spath[c].size() == 0){
        cout << "NIE\n";
        return
    }
    int ia,ib,ic;
    for(ia = 0; ia < spath[a].size(); ia++){
        ib = 0;
        if(b == a) ib = ia + 1;
        for(;ib < spath[b].size(); ib++){
            if(cross(spath[a][ia], spath[b][ib])) continue;
            ic = 0;
            if(c == a) ic = ia + 1;
            if(c == b) ic = ib + 1;
            for(; ic < spath[c].size(); ic++){
                if(cross(spath[c][ic], spath[b][ib]) || cross(spath[c][ic], spath[a][ia])) continue;
                cout << "TAK\n";
                return;
            }
        }
    }
    cout << "NIE\n";
}

int32_t main(){
    BOOST;
    int q; cin >> n >> q;
    g.resize(1000);

    int u,v,w;
    for(int i = n - 1; i > 0; i--){
        cin >> u >> v >> w;
        for(int j = 1; j < w; j++){
            n++;
            g[u].push_back(n);
            g[n].push_back(u);
            u = n;
        }
        g[u].push_back(v);
        g[v].push_back(u);
    }

    dep.assign(n + 1, 0);
    p.assign(n + 1, 0);
    jumps.assign(n + 1, vector<int>(logc, 0));

    dfs(1, 0);
    p[1] = 1;
    binary_lift();

    spath.resize(n + 1);
    for(int i = 1; i <= n; i++){
        for(int j = i + 1; j <= n; j++){
            u = i;
            v = j;
            if(dep[u] > dep[v]) swap(u,v);
            spath[path_len(u, v)].push_back({u, v});
        }
    }

    while(q--){
        solve();
    }
    return 0;
}
