// Template generated by Clank
#include<bits/stdc++.h>
using namespace std;
#define st first
#define nd second
#define all(x) x.begin(), x.end()
#define BOOST cin.tie(NULL); ios_base::sync_with_stdio(false);
// #define int ll
typedef long long ll;

// vector<int> outcomes;
vector<pair<int,int>> cards;
map<vector<int>, vector<vector<pair<int,int>>>> outcomes;

// void print(vector<int> &c){
//     int n = c.size() / 2;
//     cout << "---------\n";
//     for(int j = 0; j < 2; j++){
//         for(int i = 0; i < n; i++){
//             cout << c[i + n * j] << " ";
//         }
//         cout << "endl";
//     }
// }

void play(int &curr_max, int &curr_max_par, int &second_max, int &second_max_par, int first, int second, int idx){
    if(curr_max < first){
        curr_max = first;
        curr_max_par = idx&1;
    }
    if(second_max < second){
        second_max = second;
        second_max_par = idx&1;
    }
}

// int check_poss(vector<int> &c, int sidx, int curr_max, int second_max){
//     int curr_max_par = sidx&1;
//     int second_max_par = sidx&1;
//     for(int i = (sidx + 1) % (c.size() / 2); i != sidx; i = (i + 1) % (c.size() / 2)){
//         int b = max(c[i], c[i + c.size() / 2]);
//         int s = min(c[i], c[i + c.size() / 2]);
//         if(curr_max < s){

//             continue;
//         }
//         if(curr_max < b){

//             continue;
//         }
//         if(curr_max < b){

//             continue;
//         }
//     }
// }

// int check_score(vector<int> &c, int sidx){
    
// }

// bool check(vector<int> &c){
//     int n = c.size() / 2;
//     int score;
//     for(int i = 0; i < n; i++){
//         score = check_score(c, i);
//     }
// }

int f4(vector<pair<int,int>> &c, int endidx, int curridx, int fmax, int fpar, int smax, int spar){
    if(curridx == endidx){
        return ((endidx&1) == (fpar)) + ((endidx&1) == (spar));
    }
    int tfmax = fmax, tfpar = fpar, tsmax = smax, tspar = spar;
    play(tfmax, tfpar, tsmax, tspar, c[curridx].st, c[curridx].nd, curridx);
    play(fmax, fpar, smax, spar, c[curridx].nd, c[curridx].st, curridx);
    
    int score1 = f4(c, endidx, (curridx + 1) % (c.size()), tfmax, tfpar, tsmax, tspar);
    int score2 = f4(c, endidx, (curridx + 1) % (c.size()), fmax, fpar, smax, spar);
    if((curridx&1) == (endidx&1)){
        return max(score1, score2);
    }
    return min(score1, score2);
}

int f3(vector<pair<int,int>> &c, int sidx){
    int score1 = f4(c, sidx, (sidx + 1) % (c.size()), c[sidx].st, sidx&1, c[sidx].nd, sidx&1);
    int score2 = f4(c, sidx, (sidx + 1) % (c.size()), c[sidx].nd, sidx&1, c[sidx].st, sidx&1);
    return max(score1, score2);
}

void f2(vector<pair<int,int>> &c){
    int n  = c.size();
    vector<int> outcome(n);
    for(int i = 0; i < n; i++){
        outcome[i] = f3(c, i);
        if(outcome[i] != 1 && (!(i&1))){
            outcome[i] ^= 2;
        }
    }
    outcomes[outcome].push_back(c);
}

void f1(int kzk, vector<int> &left){
    if(kzk == left.size() / 2){
        // if(check(cards)){
        //     print(cards);
        // }
        f2(cards);
        return;
    }
    for(int i = 0; i < left.size(); i++){
        if(left[i]){
            left[i] = 0;
            cards[kzk].st = i + 1;
            for(int j = i + 1; j < left.size(); j++){
                if(left[j]){
                    left[j] = 0;
                    cards[kzk].nd = j + 1;
                    f1(kzk + 1, left);
                    left[j] = 1;
                }
            }
            left[i] = 1;
        }
    }
}

void print_cards(vector<pair<int,int>> c){
    cout << "    -------\n";
    cout << "    ";
    for(int i = 0; i < c.size(); i++){
        cout << c[i].st << " ";
    }
    cout << "\n    ";
    for(int i = 0; i < c.size(); i++){
        cout << c[i].nd << " ";
    }
    cout << "\n";
}

int32_t main(){
    BOOST;
    int n; cin >> n;
    // outcomes.resize(n);
    cards.resize(2 * n);
    // iota(all(cards), 1);
    // for(int i = 0; i < n; i++){
    //     cin >> outcomes[i];
    // }
    vector<int> left(4 * n, 1);
    f1(0, left);
    for(auto i : outcomes){
        cout << "---------------------------------------------\n";
        for(int j : i.st){
            cout << j << " ";
        }
        cout << "\n";
        cout << i.nd.size() << "\n";
        for(auto j : i.nd){
            print_cards(j);
        }
    }
    // do{
    //     if(check(cards)){
    //         print(cards);
    //     }
    // } while(next_permutation(all(cards)));
    return 0;
}
