// Template generated by Clank
#include<bits/stdc++.h>
using namespace std;
#define st first
#define nd second
#define all(x) x.begin(), x.end()
#define BOOST cin.tie(NULL); ios_base::sync_with_stdio(false);
// #define int ll
typedef long long ll;

 
int32_t main(){
    BOOST;
    int n; cin >> n;
    vector<int> nas(n);
    int maxi = 0;
    int maxi_idx = 0;
    for(int i = 0; i < n; i++){
        cin >> nas[i];
        if(nas[i] >= maxi){
            maxi = nas[i];
            maxi_idx = i;
        }
    }
    vector<int> tmpv;
    for(int i = n - 1; i > maxi_idx; i--){
        tmpv.push_back(nas.back());
        nas.pop_back();
    }
    reverse(all(nas));

    for(int i : tmpv){
        nas.push_back(i);
    }
    reverse(all(nas));
    // for(int i : nas){
    //     cout << i << " ";
    // }
    // cout << "\n";
    nas.push_back(1e9);
    vector<int> ans(n + 1, 0);
    vector<int> mstack = {n};

    int answer = 0;
    for(int i = n - 1; i >= 0; i--){
        while(nas[mstack.back()] <= nas[i]) mstack.pop_back();
        ans[i] = ans[mstack.back()] + 1;
        answer = max(answer, ans[i]);
        mstack.push_back(i);
    }
    cout << answer << "\n";
    return 0;
}
