// Template generated by Clank
#include<bits/stdc++.h>
using namespace std;
#define st first
#define nd second
#define all(x) x.begin(), x.end()
#define BOOST cin.tie(NULL); ios_base::sync_with_stdio(false);
// #define int ll
typedef long long ll;

int n, q;
int np;
vector<int> p2i;
vector<int> i2p;
vector<int> sievev;

struct AnsTracker{
    vector<int> ir; // ir[i] = ile roznic ktore zgarniaja 'i' kamieni
    vector<unordered_map<int,int>> strats// strats[i][j] = ile kamieni zgarnia skok co 'i' z przesunieciem 'j'
    int curr_max;   // odpowiedz
    AnsTracker(int n){
        ir.resize(q + 1);
        strats.resize(np + 1);
        curr_max = 0;
    }
    int get_ans(){
        return curr_max;
    }
    void del(int diff, int shift){
        diff = p2i[diff];
        assert(strats[diff].count(shift));
        int tmp = --strats[diff][shift];
        if(strats[diff][shift] == 0){
            strats[diff].erase(shift);
            ir[1]--;
        } else {
            // strats[diff][shift]--;
            ir[tmp]++;
            ir[tmp + 1]--;
        }
        if(ir[tmp + 1] == 0 && tmp + 1 == curr_max)
            curr_max--;
    }
    void add(int diff, int shift){
        diff = p2i[diff];
        int tmp = ++strats[diff][shift];
        ir[tmp - 1]--;
        ir[tmp]++;
        curr_max = max(curr_max, tmp);
    }
};

struct SituationTracker{
    
    SituationTracker(){

    }
}

void sieve(int lim){
    sievev.assign(lim + 1, 1);
    p2i.resize(lim + 1);
    sievev[0] = 0;
    sievev[1] = 0;
    for(int i = 2; i * i <= lim; i++){
        if(sievev[i]){
            p2i[i] = i2p.size();
            i2p.push_back(i);
            for(int j = i * i; j <= lim; j += i){
                sievev[j] = 0;
            }
        }
    }
    np = i2p.size();
}
 
int32_t main(){
    BOOST;
    cin >> n >> q;
    sieve(n);
    AnsTracker ans_bender(n);

    return 0;
}
