// Template generated by Clank
#include<bits/stdc++.h>
using namespace std;
#define st first
#define nd second
#define all(x) x.begin(), x.end()
#define BOOST cin.tie(NULL); ios_base::sync_with_stdio(false);
// #define int ll
typedef long long ll;

bool check(int d, vector<int> bur){
    vector<int> lag(bur.size() + 1, 0);
    int cnw = 0;
    for(int i = 0; i <= bur.size() - d; i++){
        cnw += lag[i];
        if(bur[i] < cnw) return false;
        lag[i + d] -= bur[i] - cnw;
        cnw = bur[i];
    }
    for(int i = bur.size() - d + 1; i < bur.size(); i++){
        cnw += lag[i];
        if(bur[i] != cnw) return false;
    }
    return true;
}
 
int32_t main(){
    BOOST;
    int n; cin >> n;
    vector<int> bur(n);
    ll sum = 0;
    for(int i = 0; i < n; i++){
        cin >> bur[i];
        sum += bur[i];
    }
    for(int i = n; i > 1; i--){
        if(sum % i != 0) continue;
        if(check(i, bur)){
            cout << i << "\n";
            return 0;
        }
    }
    cout << "1\n";
    return 0;
}
