// Template generated by Clank
#include<bits/stdc++.h>
using namespace std;
#define st first
#define nd second
#define all(x) x.begin(), x.end()
#define BOOST cin.tie(NULL); ios_base::sync_with_stdio(false);
// #define int ll
typedef long long ll;

int lim = 12;
map<pair<int,int>, vector<vector<int>>> poss;

void Manacher(vector<int> &s, vector<int> &p){
    int n = s.size();
    p.resize(n, 1);
    int bpi = 0;
    for(int i = 1; i < n; i++){
        if(i < bpi + p[bpi]) p[i] = min(bpi + p[bpi] - i, p[2 * bpi - i]);
        while(0 <= i - p[i] && i + p[i] < n && s[i - p[i]] == s[i + p[i]]) 
            p[i]++;
        if(bpi + p[bpi] < i + p[i]) bpi = i; 
    }
}

int max_pal(vector<int> &s){
    vector<int> t(s.size() * 2 + 1, 2);
    vector<int> p(s.size() * 2 + 1, 0);
    for(int i = 0; i < s.size(); i++){
        t[i * 2 + 1] = s[i];
    }
    Manacher(t, p);
    // cout << "MAN\n";
    // for(int i = 0; i < t.size(); i++){
    //     cout << t[i] << " " << p[i] << "\n";
    // }
    // cout << "\n";
    int maxi = 0;
    for(int i : p) maxi = max(maxi, i - 1);
    return maxi;
}


int return_ctr = 0;
void f1(int kzk, vector<int> &o){
    poss[{kzk, max_pal(o)}].push_back(o);
    if(kzk == lim){
        return_ctr++;
        if(return_ctr % 1000000 == 0)
            cout << return_ctr << endl;
        return;
    }
    o.push_back(0);
    f1(kzk + 1, o);
    o.back() = 1;
    f1(kzk + 1, o);
    o.pop_back();
}

int32_t main(){
    // BOOST;
    // vector<int> s = {0,1,0,1,1,1,0,0,0,1,0};
    // vector<int> t(s.size() * 2 + 1, 2);
    // vector<int> p(s.size() * 2 + 1, 0);
    // for(int i = 0; i < s.size(); i++){
    //     t[i * 2 + 1] = s[i];
    // }
    // Manacher(t, p);
    // for(int i = 0; i < t.size(); i++){
    //     cout << t[i] << " " << p[i] << "\n";
    // }
    vector<int> tmp;
    // vector<int> tmp = {1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0};
    // cout << max_pal(tmp) << "\n";
    f1(0, tmp);
    // for(int i = 1; i <= lim; i++){
    //     for(int j = 1; j <= i; j++){
    //         cout << "(" << i << ", " << j << ") = " << poss[{i,j}].size() << "\n";
    //     }
    // }
    // cout << "\n----------------------------------\nHEAD\n----------------------------------\n";
    for(auto i : poss){
        if(i.nd.size() == 0 || i.nd[0].size() == 0) continue;
        printf("preproc_ans[{%d, %d}] = {%d", i.st.st, i.st.nd, i.nd[0][0]);
        for(int j = 1; j < i.nd[0].size(); j++){
            printf(",%d",i.nd[0][j]);
        }
        printf("};\n");
        // cout << "(" << i.st.st << ", " << i.st.nd << ") = " << i.nd.size() << "\n";
        // for(auto j : i.nd){
        //     cout << "    ";
        //     for(int h : j){
        //         cout << h;
        //     }
        //     cout << "\n";
        // }
    }
    return 0;
}
