// Template generated by Clank
#include<bits/stdc++.h>
using namespace std;
#define st first
#define nd second
#define all(x) x.begin(), x.end()
#define BOOST cin.tie(NULL); ios_base::sync_with_stdio(false);
// #define int ll
typedef long long ll;

 
int32_t main(){
    BOOST;
    int n, q; cin >> n >> q;
    ll mod = 1e9 + 7;
    vector<pair<ll,ll>> e(n + 2);
    for(int i = 1; i <= n; i++){
        cin >> e[i].st >> e[i].nd;
    }

    ll x, l, r;
    bool modapp = 0;
    while(q--){
        modapp = 0;
        cin >> x >> l >> r;
        for(int i = l + 1; i <= r; i++){
            if(modapp){
                if(e[i].nd > 1){
                    x = (x * e[i].nd) % mod;
                } else {
                    x = (x + e[i].st) % mod;
                }
            } else {
                x = max(x + e[i].st, x * e[i].nd);
            }
            if(x >= mod){
                x %= mod;
                modapp = 1;
            }
        }
        cout << x << "\n";
    }
    return 0;
}
