// Template generated by Clank
#include<bits/stdc++.h>
using namespace std;
#define st first
#define nd second
#define all(x) x.begin(), x.end()
#define BOOST cin.tie(NULL); ios_base::sync_with_stdio(false);
// #define int ll
typedef long long ll;

int RA(int l, int r){
    return (rand() % (r - l + 1)) + l;    
}
 
int32_t main(){
    BOOST;
    int n = 10000, q = 10000;
    cout << n << " " << q << "\n";
    for(int i = 0; i < n; i++){
        if(RA(0, 1)){
            cout << RA(0, 10000) << " " << RA(0, 1) << "\n";
        } else {
            cout << RA(0, 1e9 + 7) << " " << RA(0, 1e9 + 7) << "\n";
        }
    }
    int l, r;
    while(q--){
        l = RA(0, n/2);
        r = RA(l + 1, n);
        cout << RA(0, 10000) << " " << l << " " << r << "\n";
    }
    return 0;
}
