// Template generated by Clank
#include<bits/stdc++.h>
using namespace std;
#define st first
#define nd second
#define all(x) x.begin(), x.end()
#define BOOST cin.tie(NULL); ios_base::sync_with_stdio(false);
// #define int ll
typedef long long ll;

struct SegTree{
    int n;
    int shift = 1;
    vector<ll> t;
    vector<ll> p;
    SegTree(int inn, vector<ll> &a) : n(inn) {
        while(shift < n) shift <<= 1;
        t.resize(2 * shift);
        p.resize(2 * shift);
        for(int i = 0; i < a.size(); i++) t[i + shift] = a[i];
        for(int i = shift - 1; i > 0; i--) t[i] = t[i << 1] + t[(i << 1) ^ 1];
    }

    void push(int idx){
        t[idx] += p[idx];
        if(idx < shift){
            p[idx << 1] += p[idx];
            p[(idx << 1) ^ 1] += p[idx];
        }
        p[idx] = 0;
    }

    void update_(int idx, int ql, int qr, int cl, int cr, ll val){
        if(cr <= ql || qr <= cl) return;
        if(ql <= cl && cr <= qr){
            p[idx] += val;
            push(idx);
            return;
        }
        push(idx);
        update_(idx << 1, ql, qr, cl, (cl + cr)/2, val);
        update_((idx << 1) + 1, ql, qr, (cl + cr)/2, cr, val);
        t[idx] = t[idx << 1] + t[(idx << 1) ^ 1];
    }

    ll query_(int idx, int ql, int qr, int cl, int cr){
        if(cr <= ql || qr <= cl) return 0;
        push(idx);
        if(ql <= cl && cr <= qr){
            return t[idx];
        }
        return query_(idx << 1, ql, qr, cl, (cl + cr)/2) + query_((idx << 1) + 1, ql, qr, (cl + cr)/2, cr);
    }
    
    void update(int ql, int qr,int val){
        update_(1, ql, qr, 0, shift, val);
    }

    ll query(int ql, int qr){
        return query_(1, ql, qr, 0, shift);
    }
};
 
int32_t main(){
    BOOST;
    int n,m; cin >> n >> m;
    vector<ll> a(n, 0);
    // for(int i = 0; i < n; i++){
    //     cin >> a[i];
    // }

    SegTree sgt(n, a);

    int action, l, r, v;
    while(m--){
        cin >> action;
        // cout << action << "\n";
        if(action == 1){
            cin >> l >> r >> v;
            sgt.update(l, r, v);
        } else {
            cin >> l;
            r = l + 1;
            cout << sgt.query(l, r) << "\n";
        }
    }
    return 0;

}
