// Template generated by Clank
#include<bits/stdc++.h>
using namespace std;
#define st first
#define nd second
#define all(x) x.begin(), x.end()
#define BOOST cin.tie(NULL); ios_base::sync_with_stdio(false);
// #define int ll
typedef long long ll;

struct SegTree{
    int n; 
    int shift = 1;
    vector<int> t;
    SegTree(int inn) : n(inn) {
        while(shift < n) shift <<= 1;
        t.resize(2 * shift, 0);
        // for(int i = 0; i < n; i++) t[i + shift] = a[i];
    }

    void update(int l, int r, int val){
        for(l += shift, r += shift; l < r; l >>= 1, r >>= 1){
            if(l & 1){
                t[l] = max(t[l], val);
                l++;
            }
            if(r & 1){
                r--;
                t[r] = max(t[r], val);
            }
        }
    }

    int query(int idx){
        int ans = 0;
        for(idx += shift; idx >= 1; idx >>= 1){
            ans = max(ans, t[idx]);
        }
        return ans;
    }
};

int32_t main(){
    BOOST;
    int n, m; cin >> n >> m;
    SegTree ds(n);
    
    int action, l, r, v, idx;
    while(m--){
        cin >> action;
        if(action == 1){
            cin >> l >> r >> v;
            ds.update(l, r, v);
        } else {
            cin >> idx;
            cout << ds.query(idx) << "\n";
        }
    }
    return 0;
}
