// Template generated by Clank
#include<bits/stdc++.h>
using namespace std;
#define st first
#define nd second
#define all(x) x.begin(), x.end()
#define BOOST cin.tie(NULL); ios_base::sync_with_stdio(false);
// #define int ll
typedef long long ll;

struct SegTree{
    int n;
    int shift = 1;
    vector<int> t;
    
    SegTree(int inn) : n(inn){
        while(shift < n) shift <<= 1;
        t.resize(shift * 2);
    }
};

int32_t main(){
    BOOST;
    
    return 0;
}
