// This file was generated by Clank
#include<bits/stdc++.h>
#define st first
#define nd second
#define all(x) x.begin(), x.end()
#define BOOST cin.tie(NULL); ios_base::sync_with_stdio(false);
 
#define int ll
typedef long long ll;

using namespace std;
template <typename T> struct tag:reference_wrapper <T>{ using reference_wrapper <T>::reference_wrapper; };
template <typename T1, typename T2> static inline tag <ostream> operator<<(tag <ostream> os, pair<T1, T2> const& p){ return os.get()<<"{"<<p.first<<", "<<p.second<<"}", os;}
template <typename Other> static inline tag <ostream> operator<<(tag <ostream> os, Other const& o){ os.get()<<o; return os; }
template <typename T> static inline tag <ostream> operator <<(tag <ostream> os, vector <T> const& v){ os.get()<<"["; for (int i=0; i<v.size(); i++) if (i!=v.size()-1) os.get()<<v[i]<<", "; else os.get()<<v[i]; return os.get()<<"]", os; }
template <typename T> static inline tag <ostream> operator <<(tag <ostream> os, set <T> const& s){ vector <T> v; for (auto i: s) v.push_back(i); os.get()<<"["; for (int i=0; i<v.size(); i++) if (i!=v.size()-1) os.get()<<v[i]<<", "; else os.get()<<v[i]; return os.get()<<"]", os; }


void solve(){
    int n; 
    cin >> n;
    vector<int> a(n);
    ll tans = 0;
    for(int i = 0; i < n; i++){
        cin >> a[i];
        if(i&1){
            tans -= a[i];
        } else {
            tans += a[i];
        }
    }
    ll shift = 0;
    ll bigi = -2e9;
    int bidx = -1;
    int l = 0, r = 0;
    for(int i = 1; i < n; i++){
        shift++;
        if(i&1){
            if(2 * bigi + shift < 2 * a[i]){
                bigi = a[i];
                shift = 0;
                bidx = i;
            }
        } else {
            if(2 * (a[l] - a[r]) + abs(r - l) < 2 * (bigi - a[i]) + shift){
                l = bidx;
                r = i;
            }
        }
    }
    // cout << l << " - " << r << "\n";
    int start = n - 1;
    shift = 0;
    bigi = -2e9;
    if(n&1){
        tans += start;
        start--;
    } else {
        tans += start - 1;
    }
    for(int i = start; i >= 0; i--){
        shift++;
        if(i&1){
            if(2 * bigi + shift < 2 * a[i]){
                bigi = a[i];
                shift = 0;
                bidx = i;
            }
        } else {
            if(2 * (a[l] - a[r]) + abs(l - r) < 2 * (bigi - a[i]) + shift){
                l = bidx;
                r = i;
            }
        }
    }
    // cout << l << " - " << r << "\n";
    swap(a[l],a[r]);
    ll ans = abs(r - l);
    // cout << a << "\n";
    for(int i = 0; i < n; i++){
        if(i&1){
            ans -= a[i];
        } else {
            ans += a[i];
        }
    }
    // cout << tans << " " << l << " - " << r << "\n";
    cout << max(ans,tans) << "\n";
}

 
int32_t main(){
    BOOST;
 
    int q = 1; cin >> q;
    while(q--){
        solve();
    }
    return 0;
}
