// This file was generated by Clank
#include<bits/stdc++.h>
#define st first
#define nd second
#define all(x) x.begin(), x.end()
#define BOOST cin.tie(NULL); ios_base::sync_with_stdio(false);
 
// #define int ll
typedef long long ll;

using namespace std;
template <typename T> struct tag:reference_wrapper <T>{ using reference_wrapper <T>::reference_wrapper; };
template <typename T1, typename T2> static inline tag <ostream> operator<<(tag <ostream> os, pair<T1, T2> const& p){ return os.get()<<"{"<<p.first<<", "<<p.second<<"}", os;}
template <typename Other> static inline tag <ostream> operator<<(tag <ostream> os, Other const& o){ os.get()<<o; return os; }
template <typename T> static inline tag <ostream> operator <<(tag <ostream> os, vector <T> const& v){ os.get()<<"["; for (int i=0; i<v.size(); i++) if (i!=v.size()-1) os.get()<<v[i]<<", "; else os.get()<<v[i]; return os.get()<<"]", os; }
template <typename T> static inline tag <ostream> operator <<(tag <ostream> os, set <T> const& s){ vector <T> v; for (auto i: s) v.push_back(i); os.get()<<"["; for (int i=0; i<v.size(); i++) if (i!=v.size()-1) os.get()<<v[i]<<", "; else os.get()<<v[i]; return os.get()<<"]", os; }

struct Node{
    int sval;
    int siz;
};

void solve(){
    int n, k; 
    cin >> n >> k;
    vector<int> a(n);
    for(int i = 0; i < n; i++){
        cin >> a[i];
    }
    a.push_back(-1);
    sort(all(a));
    int curr_val = 1e9;
    int curr_no = 1;
    int ans = 0;
    int shift = 0;
    vector<Node> ms;
    Node tnode;
    for(int i = n; i >= 0; i--){
        if(a[i] == curr_val){
            curr_no++;
        } else {
            tnode = {curr_val, curr_no};
            int tans = 0;
            if(tnode.siz > k){
                tans = tnode.siz - k;
                ans = max(ans, tans);
            }
            while(ms.size() > 0 && tnode.sval + tans >= ms.back().sval){
                tnode.siz += ms.back().siz;
                if(tnode.siz > k){
                    tans = tnode.siz - k;
                    ans = max(ans, tans);
                }
                ms.pop_back();
            }
            ms.push_back(tnode);
            curr_no = 1;
            curr_val = a[i];
        }
    }
    cout << ans << "\n";
}

 
int32_t main(){
    BOOST;
 
    int q = 1; cin >> q;
    while(q--){
        solve();
    }
    return 0;
}
