// Template generated by Clank
#include<bits/stdc++.h>
using namespace std;
#define st first
#define nd second
#define all(x) x.begin(), x.end()
#define BOOST cin.tie(NULL); ios_base::sync_with_stdio(false);

// #define int ll

typedef long long ll;

const int N = 250000;
int shift = sqrt(N);
vector<int> deg;
vector<int> job;
set<int> alive;
vector<int> todel;
vector<pair<int,int>> miss;
vector<int> potpre;

void add_job(int lvl, int len){
    assert(job[lvl] == 0);
    job[lvl] = len;
    deg[lvl + len]++;
}

int job_done(int lvl){
    miss.push_back({lvl, job[lvl]});
    deg[lvl + job[lvl]]--;
    if(deg[lvl + job[lvl]] == 0) return lvl + job[lvl];
    return 0; 
}

void div2(int l, int r){
    auto itl = alive.lower_bound(l);
    if(itl == alive.end()) return;
    auto ahead = itl;
    ahead++;
    auto itr = alive.upper_bound(r);
    while(itl != itr && ahead != itr){
        add_job(*itl, (*ahead) - (*itl));
        todel.push_back(*itl);
        ahead++;
        itl = ahead;
        ahead++;
    }
    while(!todel.empty()){
        alive.erase(todel.back());
        todel.pop_back();
    }
}

void make_group(int l, int r){
    auto itl = alive.lower_bound(l);
    if(itl == alive.end()) return;
    auto ahead = itl;
    ahead++;
    auto itr = alive.upper_bound(r);
    if(itl == itr) return;
    itr--;
    while(itl != itr){
        add_job(*itl, (*ahead) - (*itl));
        todel.push_back(*itl);
        itl = ahead;
        ahead++;
    }
    while(!todel.empty()){
        alive.erase(todel.back());
        todel.pop_back();
    }
}

void print(set<int> *os, string what){
    cout << what << "\n";
    for(auto i : (*os)){
        cout << i << " ";
    }
    cout << endl;
}

void compute_strategy(){
    set<int> ready;
    for(int i = 1; i < N; i++){
        if(deg[i] == 0) ready.insert(i);
    }
    int last_mission = 1e9;
    while(!ready.empty()){
        if(last_mission < *(ready.begin())){
            last_mission = 1e9;
        }
        auto it = ready.upper_bound(last_mission);
        it--;
        if(job[*it]){
            last_mission = *it;
            int tmp = job_done(*it);
            if(tmp) ready.insert(tmp);
        }
        ready.erase(*it);
    }
}

int32_t main(){
    BOOST;
    deg.assign(N + 10, 0);
    job.assign(N + 10, 0);
    potpre.assign(N + 10, 1);
    for(int i = 1; i <= N + 1; i++) alive.insert(i);
    
    shift = 40;
    for(int i = 1; i + shift - 1 <= N; i += shift){
        make_group(i, i + shift - 1);
    }
    shift = 2000;
    for(int i = 1; i + shift - 1 <= N; i += shift){
        make_group(i, i + shift - 1);
    }
    make_group(1, N);

    compute_strategy();
    cout << miss.size() << "\n";
    for(auto i : miss){
        cout << i.st << " " << i.nd << "\n";
    }
    return 0;
}
