// This file was generated by Clank
#include<bits/stdc++.h>
#define st first
#define nd second
#define all(x) x.begin(), x.end()
#define BOOST cin.tie(NULL); ios_base::sync_with_stdio(false);
 
#define int ll
typedef long long ll;

using namespace std;
template <typename T> struct tag:reference_wrapper <T>{ using reference_wrapper <T>::reference_wrapper; };
template <typename T1, typename T2> static inline tag <ostream> operator<<(tag <ostream> os, pair<T1, T2> const& p){ return os.get()<<"{"<<p.first<<", "<<p.second<<"}", os;}
template <typename Other> static inline tag <ostream> operator<<(tag <ostream> os, Other const& o){ os.get()<<o; return os; }
template <typename T> static inline tag <ostream> operator <<(tag <ostream> os, vector <T> const& v){ os.get()<<"["; for (int i=0; i<v.size(); i++) if (i!=v.size()-1) os.get()<<v[i]<<", "; else os.get()<<v[i]; return os.get()<<"]", os; }
template <typename T> static inline tag <ostream> operator <<(tag <ostream> os, set <T> const& s){ vector <T> v; for (auto i: s) v.push_back(i); os.get()<<"["; for (int i=0; i<v.size(); i++) if (i!=v.size()-1) os.get()<<v[i]<<", "; else os.get()<<v[i]; return os.get()<<"]", os; }

void update_ans(int *ans, int idxl, int idxr, vector<pair<int,int>> &left, vector<pair<int,int>> &right){
    if(idxr >= right.size() || idxr < 0 || idxl + idxr >= right.size()) return;
    (*ans) = max((*ans), min(left[idxl].st + right[idxr].st, left[idxl].nd + right[idxr].nd));
}

int calc_ans(int idxl, int idxr, vector<pair<int,int>> &left, vector<pair<int,int>> &right){
    if(idxr >= right.size() || idxr < 0 || idxl + idxr >= right.size()) return -1;
    return min(left[idxl].st + right[idxr].st, left[idxl].nd + right[idxr].nd);
}

void solve(){
    int n, l, r; 
    cin >> n >> l >> r;
    vector<int> a(n);
    for(int i = 0; i < n; i++){
        cin >> a[i];
    }
    sort(all(a));
    pair<int,int> pzero = {0,0};
    pair<int,int> tmpp;
    vector<pair<int,int>> left;
    vector<pair<int,int>> right;
    left.push_back(pzero);
    right.push_back(pzero);
    for(int i = 0; i < n; i++){
        tmpp.st = left.back().st + l - a[i];
        tmpp.nd = left.back().nd + r - a[i];
        left.push_back(tmpp);
        tmpp.st = right.back().st + a[n - 1 - i] - l;
        tmpp.nd = right.back().nd + a[n - 1 - i] - r;
        right.push_back(tmpp);
    }
    // cout << left << "\n" << right << "\n";
    int ans = 0;
    int idxl, idxr = 0;
    for(idxl = 0; idxl <= n; idxl++){
        // cout << idxl << " - " << idxr << "\n";
        while(idxl + idxr > n) idxr--;
        
        update_ans(&ans, idxl, idxr, left, right);
        // ans = max(ans, min(left[idxl].st + right[idxr].st, left[idxl].nd + right[idxr].nd));
        while(calc_ans(idxl, idxr - 1, left, right) > ans){
            idxr--;
            // ans = max(ans, min(left[idxl].st + right[idxr].st, left[idxl].nd + right[idxr].nd));
            update_ans(&ans, idxl, idxr, left, right);
        }
        while(calc_ans(idxl, idxr + 1, left, right) >= ans){
            idxr++;
            update_ans(&ans, idxl, idxr, left, right);
            // ans = max(ans, min(left[idxl].st + right[idxr].st, left[idxl].nd + right[idxr].nd));
        }
        update_ans(&ans, idxl, idxr - 1, left, right);
        update_ans(&ans, idxl, idxr + 1, left, right);
        // cout << idxl << " - " << idxr << "\n";
    }
    cout << ans << "\n";
}

 
int32_t main(){
    BOOST;
 
    int q = 1; cin >> q;
    while(q--){
        solve();
    }
    return 0;
}
