// This file was generated by Clank
#include<bits/stdc++.h>
#define st first
#define nd second
#define all(x) x.begin(), x.end()
#define BOOST cin.tie(NULL); ios_base::sync_with_stdio(false);
 
// #define int ll
typedef long long ll;

using namespace std;
template <typename T> struct tag:reference_wrapper <T>{ using reference_wrapper <T>::reference_wrapper; };
template <typename T1, typename T2> static inline tag <ostream> operator<<(tag <ostream> os, pair<T1, T2> const& p){ return os.get()<<"{"<<p.first<<", "<<p.second<<"}", os;}
template <typename Other> static inline tag <ostream> operator<<(tag <ostream> os, Other const& o){ os.get()<<o; return os; }
template <typename T> static inline tag <ostream> operator <<(tag <ostream> os, vector <T> const& v){ os.get()<<"["; for (int i=0; i<v.size(); i++) if (i!=v.size()-1) os.get()<<v[i]<<", "; else os.get()<<v[i]; return os.get()<<"]", os; }
template <typename T> static inline tag <ostream> operator <<(tag <ostream> os, set <T> const& s){ vector <T> v; for (auto i: s) v.push_back(i); os.get()<<"["; for (int i=0; i<v.size(); i++) if (i!=v.size()-1) os.get()<<v[i]<<", "; else os.get()<<v[i]; return os.get()<<"]", os; }

int infi = 1e9;
// int tinfi = 1e9;

void add_mex(vector<int> &ans, pair<int,int> lr, int k){
    vector<int> got(k + 10, 0);
    vector<int> marked;
    for(int i = lr.nd; i >= lr.st; i--){
        if(ans[i] == infi) {
            marked.push_back(i);
            // ans[i] = k - 1;
        } else if(ans[i] == k){
            ans[i] = k + 1;
        } else {
            got[ans[i]]++;
        }
    }
    for(int i = 0; i < k; i++){
        if(got[i] == 0){
            assert(marked.size() > 0);
            ans[marked.back()] = i;
            marked.pop_back();
        }
    }
}

void solve(){
    int n, k, q; 
    cin >> n >> k >> q;
    vector<pair<int,int>> mini;
    vector<pair<int,int>> mexi;
    pair<int,int> tmpp;
    int tmp;
    for(int i = 0; i < q; i++){
        cin >> tmp >> tmpp.st >> tmpp.nd;
        if(tmp == 1){
            mini.push_back(tmpp);
        } else {
            mexi.push_back(tmpp);
        }
    }
    vector<int> ans(n + 1, infi);
    for(int i = 0; i < mini.size(); i++){
        for(int j = mini[i].st; j <= mini[i].nd; j++){
            ans[j] = k;
        }
    }

    sort(all(mexi));
    for(int i = 0; i < mexi.size(); i++){
        add_mex(ans, mexi[i], k);
    }
    // for(int i = 0; i < mexi.size(); i++){
    //     add_mex(ans, maxi[i], k);
    // }
    for(int i = 1; i <= n; i++){
        cout << ans[i] << " ";
    }
    cout << "\n";
}

 
int32_t main(){
    BOOST;
 
    int q = 1; cin >> q;
    while(q--){
        solve();
    }
    return 0;
}
