// This file was generated by Clank
#include<bits/stdc++.h>
#define st first
#define nd second
#define all(x) x.begin(), x.end()
#define BOOST cin.tie(NULL); ios_base::sync_with_stdio(false);
 
// #define int ll
typedef long long ll;

using namespace std;
template <typename T> struct tag:reference_wrapper <T>{ using reference_wrapper <T>::reference_wrapper; };
template <typename T1, typename T2> static inline tag <ostream> operator<<(tag <ostream> os, pair<T1, T2> const& p){ return os.get()<<"{"<<p.first<<", "<<p.second<<"}", os;}
template <typename Other> static inline tag <ostream> operator<<(tag <ostream> os, Other const& o){ os.get()<<o; return os; }
template <typename T> static inline tag <ostream> operator <<(tag <ostream> os, vector <T> const& v){ os.get()<<"["; for (int i=0; i<v.size(); i++) if (i!=v.size()-1) os.get()<<v[i]<<", "; else os.get()<<v[i]; return os.get()<<"]", os; }
template <typename T> static inline tag <ostream> operator <<(tag <ostream> os, set <T> const& s){ vector <T> v; for (auto i: s) v.push_back(i); os.get()<<"["; for (int i=0; i<v.size(); i++) if (i!=v.size()-1) os.get()<<v[i]<<", "; else os.get()<<v[i]; return os.get()<<"]", os; }


void solve(){
    int n; 
    cin >> n;
    vector<int> a(n);
    int maxi = 0, maxidx = 0, mini = 1e9, minidx = 0;
    for(int i = 0; i < n; i++){
        cin >> a[i];
        if(a[i] == n){
            maxidx = i;
        }
        if(a[i] == 1){
            minidx = i;
        }
    }
    string s;
    cin >> s;
    if(s[0] == '1' || s[n - 1] == '1' || s[minidx] == '1' || s[maxidx] == '1'){
        cout << "-1\n";
        return;
    }
    cout << "5\n";
    cout << "1 " << minidx + 1 << "\n";
    cout << "1 " << maxidx + 1 << "\n";
    cout << minidx + 1 << " " << n << "\n";
    cout << maxidx + 1 << " " << n << "\n";
    cout << min(maxidx, minidx) + 1  << " " << max(maxidx, minidx) + 1 << "\n";
}

 
int32_t main(){
    BOOST;
 
    int q = 1; cin >> q;
    while(q--){
        solve();
    }
    return 0;
}
