// This file was generated by Clank
#include<bits/stdc++.h>
#define st first
#define nd second
#define all(x) x.begin(), x.end()
#define BOOST cin.tie(NULL); ios_base::sync_with_stdio(false);
 
// #define int ll
typedef long long ll;

using namespace std;
template <typename T> struct tag:reference_wrapper <T>{ using reference_wrapper <T>::reference_wrapper; };
template <typename T1, typename T2> static inline tag <ostream> operator<<(tag <ostream> os, pair<T1, T2> const& p){ return os.get()<<"{"<<p.first<<", "<<p.second<<"}", os;}
template <typename Other> static inline tag <ostream> operator<<(tag <ostream> os, Other const& o){ os.get()<<o; return os; }
template <typename T> static inline tag <ostream> operator <<(tag <ostream> os, vector <T> const& v){ os.get()<<"["; for (int i=0; i<v.size(); i++) if (i!=v.size()-1) os.get()<<v[i]<<", "; else os.get()<<v[i]; return os.get()<<"]", os; }
template <typename T> static inline tag <ostream> operator <<(tag <ostream> os, set <T> const& s){ vector <T> v; for (auto i: s) v.push_back(i); os.get()<<"["; for (int i=0; i<v.size(); i++) if (i!=v.size()-1) os.get()<<v[i]<<", "; else os.get()<<v[i]; return os.get()<<"]", os; }

int ask(int l, int r){
    cout << "? " << l << " " << r << "\n";
    cout.flush();
    int ans;
    cin >> ans;
    return ans;
}

void answer(int val){
    cout << "! " << val << "\n";
    cout.flush();
    return;
}

bool cmp(pair<int,int> a, pair<int,int> b){
    if(a.st != b.st) return a.st < b.st;
    return a.nd > b.nd;
}

void solve(){
    int n, q; 
    cin >> n >> q;
    vector<pair<int,int>> a(q);
    for(int i = 0; i < q; i++){
        cin >> a[i].st >> a[i].nd;
    }
    sort(all(a), cmp);
    vector<pair<int,int>> ts;
    ts.push_back({-1,-1});

    for(auto s : a){
        if(ts.back().nd < s.nd){
            ts.push_back(s);
        }
    }
    ts.erase(ts.begin());
    if(ts.size() < 30){
        int ans = 0;
        for(auto s : ts){
            ans = max(ans, ask(s.st, s.nd));
        }
        // cout << ans << "\n";
        answer(ans);
        return;
    }

    int ans = 0;
    int po = 0, ko = ts.size() - 1, sr;
    int lans, rans;
    while(po < ko){
        sr = (po + ko) / 2;
        lans = ask(1, ts[sr].nd);
        rans = ask(ts[sr].st, n);
        ans = max(ans, min(lans, rans));
        if(lans > rans){
            ko = sr - 1;
        } else {
            po = sr + 1;
        }
    }
    if(po < ts.size()) ans = max(ans, ask(ts[po].st, ts[po].nd));
    if(0 <= ko) ans = max(ans, ask(ts[ko].st, ts[ko].nd));
    answer(ans);
}

 
int32_t main(){
    // BOOST;
 
    int q = 1; cin >> q;
    while(q--){
        solve();
    }
    return 0;
}
