// This file was generated by Clank
#include<bits/stdc++.h>
#define st first
#define nd second
#define all(x) x.begin(), x.end()
#define BOOST cin.tie(NULL); ios_base::sync_with_stdio(false);
 
// #define int ll
typedef long long ll;
 
using namespace std;
template <typename T> struct tag:reference_wrapper <T>{ using reference_wrapper <T>::reference_wrapper; };
template <typename T1, typename T2> static inline tag <ostream> operator<<(tag <ostream> os, pair<T1, T2> const& p){ return os.get()<<"{"<<p.first<<", "<<p.second<<"}", os;}
template <typename Other> static inline tag <ostream> operator<<(tag <ostream> os, Other const& o){ os.get()<<o; return os; }
template <typename T> static inline tag <ostream> operator <<(tag <ostream> os, vector <T> const& v){ os.get()<<"["; for (int i=0; i<v.size(); i++) if (i!=v.size()-1) os.get()<<v[i]<<", "; else os.get()<<v[i]; return os.get()<<"]", os; }
template <typename T> static inline tag <ostream> operator <<(tag <ostream> os, set <T> const& s){ vector <T> v; for (auto i: s) v.push_back(i); os.get()<<"["; for (int i=0; i<v.size(); i++) if (i!=v.size()-1) os.get()<<v[i]<<", "; else os.get()<<v[i]; return os.get()<<"]", os; }
 
 
void solve(){
    int n; 
    cin >> n;
    vector<int> a[2];
    a[0].resize(n + 2);
    a[1].resize(n + 2);
    
    // a[0][0] = 1e9;
    for(int i = 1; i <= n; i++){
        cin >> a[0][i];
        
    }
    for(int i = 1; i <= n; i++){
        cin >> a[1][i];
    }
    // a[n + 1][0] = 1e9;
    // a[0][1] = 1e9;
    vector<int> mini[2];
    vector<int> maxi[2];
    mini[0].resize(n + 2);
    mini[1].resize(n + 2);
    maxi[0].resize(n + 2);
    maxi[1].resize(n + 2);
    // a[0][0] = 1e9;
    mini[0][0] = 1e9;
    maxi[0][0] = 0;
    for(int i = 1; i <= n; i++){
        mini[0][i] = min(mini[0][i - 1], a[0][i]);
        maxi[0][i] = max(maxi[0][i - 1], a[0][i]);
    }
    mini[0][n + 1] = 0;
    maxi[0][n + 1] = 1e9;
 
    mini[1][n + 1] = 1e9;
    maxi[1][n + 1] = 0;
    for(int i = n; i >= 1; i--){
        mini[1][i] = min(mini[1][i + 1], a[1][i]);
        maxi[1][i] = max(maxi[1][i + 1], a[1][i]);
    }
    mini[1][0] = 0;
    maxi[1][0] = 1e9;
    
 
 
    int min0 = n, min1 = 1, max0 = 0, max1 = n + 1;
    int lastmax = 0;
    ll ans = 0;
    for(int l = 1; l <= 2 * n; l++){
        while(mini[0][min0] < l) min0--;
        while(mini[1][min1] < l) min1++;
        if(min0 < min1) break;
        while((max0 < min1 || min0 < max1 || max0 < max1) && lastmax <= 2 * n){
            // cout << l << " xDDD " << lastmax << " " << min0 << " " << max0 << " " << min1 << " " << max1 << "\n";
            lastmax++;
            while(maxi[0][max0 + 1] <= lastmax) max0++;
            while(maxi[1][max1 - 1] <= lastmax) max1--;
        }
        // cout << l << " " << lastmax << " " << min0 << " " << max0 << " " << min1 << " " << max1 << "\n";
        ans += 2*n - max(lastmax, l) + 1;
        // lastmax = max(lastmax, l);
 
    }
    cout << ans << "\n";
}
 
 
int32_t main(){
    BOOST;
 
    int q = 1; cin >> q;
    while(q--){
        solve();
    }
    return 0;
}