// This file was generated by Clank
#include<bits/stdc++.h>
#define st first
#define nd second
#define all(x) x.begin(), x.end()
#define BOOST cin.tie(NULL); ios_base::sync_with_stdio(false);
 
#define int ll
typedef long long ll;

using namespace std;
template <typename T> struct tag:reference_wrapper <T>{ using reference_wrapper <T>::reference_wrapper; };
template <typename T1, typename T2> static inline tag <ostream> operator<<(tag <ostream> os, pair<T1, T2> const& p){ return os.get()<<"{"<<p.first<<", "<<p.second<<"}", os;}
template <typename Other> static inline tag <ostream> operator<<(tag <ostream> os, Other const& o){ os.get()<<o; return os; }
template <typename T> static inline tag <ostream> operator <<(tag <ostream> os, vector <T> const& v){ os.get()<<"["; for (int i=0; i<v.size(); i++) if (i!=v.size()-1) os.get()<<v[i]<<", "; else os.get()<<v[i]; return os.get()<<"]", os; }
template <typename T> static inline tag <ostream> operator <<(tag <ostream> os, set <T> const& s){ vector <T> v; for (auto i: s) v.push_back(i); os.get()<<"["; for (int i=0; i<v.size(); i++) if (i!=v.size()-1) os.get()<<v[i]<<", "; else os.get()<<v[i]; return os.get()<<"]", os; }


int f1(int X, int V, int I, int IX, int IV, int TQ, int q, int qq, int qx, int iq, int iqx){
    // printf("X: %lld, V: %lld, I: %lld, IX: %lld, IV: %lld, TQ: %lld, q: %lld, qq: %lld, qx: %lld, iq: %lld, iqx: %lld\n", X, V, I, IX, IV, TQ, q, qq, qx, iq, iqx);
    int cx, cv, ci;
    int sum = X * 10 + V * 5 + I * 1 + IX * 9 + IV * 4;
    cin >> cx >> cv >> ci;
    int rx, rv, ri;
    ri = min(TQ, ci);
    rv = min(cv, max(TQ - ri, 0LL));
    rx = max(TQ - ri - rv, 0LL);
    // printf("rx %lld   rv %lld   ri %lld\n", rx, rv, ri);
    sum += ri + 5 * rv + 10 * rx;
    ci = ri;
    int cxv = rv + rx;

    int tmp;
    if(ci >= qx){
        ci -= qx;
        sum -= 2 * qx;
        TQ -= qx;
    } else {
        TQ -= ci;
        sum -= 2 * ci;
        ci = 0;
    }

    if(cxv >= iq){
        cxv -= iq;
        sum -= 2 * iq;
        TQ -= iq;
    } else {
        sum -= 2 * cxv;
        TQ -= cxv;
        cxv = 0;
    }

    TQ -= iqx;
    sum -= 2 * iqx;
    tmp = min({cxv, ci, qq});
    sum -= tmp * 2;
    return sum;
}

void solve(){
    int n, t; 
    cin >> n >> t;
    string s;
    cin >> s;
    s = "VVV" + s + "I";
    n = s.size();
    int X = 0,V = 0,I = 0, Q = 0;
    int IX = 0, IV = 0;
    int iq = 0, qx = 0, qq = 0, q = 0, iqx = 0;

    char lastc = 'V';
    int qctr = 0;
    for(int i = 3; i < n; i++){
        if(s[i] == '?'){
            qctr++;
            Q++;
            continue;
        }

        if((s[i] == 'X' || s[i] == 'V') && s[i - 1] == '?'){
            if(lastc == 'I'){
                if(qctr == 1){
                    iqx++;
                } else {
                    iq++;
                    qx++;
                    qq += (qctr - 2) / 2;
                    q += (qctr - 2) & 1;
                }
            } else {
                qx++;
                qq += (qctr - 1) / 2;
                q += (qctr - 1) & 1;
            }
            qctr = 0;
        }

        if(s[i] == 'X'){
            if(s[i - 1] == 'I'){
                I--;
                IX++;                
            } else {
                X++;
            }
        }
        if(s[i] == 'V'){
            if(s[i - 1] == 'I'){
                I--;
                IV++;                
            } else {
                V++;
            }
        }
        
        if(s[i] == 'I'){
            I++;
            if(qctr > 0){
                if(lastc != 'I'){
                    qq += qctr / 2;
                    q += qctr & 1;
                } else {
                    iq++;
                    qq += (qctr - 1) / 2;
                    q += (qctr - 1) & 1;
                }
                qctr = 0;
            }
        }
        lastc = s[i];
    }
    I--;
    
    while(t--){
        cout << f1(X, V, I, IX, IV, Q, q, qq, qx, iq, iqx) << "\n";
    }
}

 
int32_t main(){
    BOOST;
 
    int q = 1; cin >> q;
    while(q--){
        solve();
    }
    return 0;
}
