// This file was generated by Clank
#include<bits/stdc++.h>
#define st first
#define nd second
#define all(x) x.begin(), x.end()
#define BOOST cin.tie(NULL); ios_base::sync_with_stdio(false);
 
// #define int ll
typedef long long ll;

using namespace std;
template <typename T> struct tag:reference_wrapper <T>{ using reference_wrapper <T>::reference_wrapper; };
template <typename T1, typename T2> static inline tag <ostream> operator<<(tag <ostream> os, pair<T1, T2> const& p){ return os.get()<<"{"<<p.first<<", "<<p.second<<"}", os;}
template <typename Other> static inline tag <ostream> operator<<(tag <ostream> os, Other const& o){ os.get()<<o; return os; }
template <typename T> static inline tag <ostream> operator <<(tag <ostream> os, vector <T> const& v){ os.get()<<"["; for (int i=0; i<v.size(); i++) if (i!=v.size()-1) os.get()<<v[i]<<", "; else os.get()<<v[i]; return os.get()<<"]", os; }
template <typename T> static inline tag <ostream> operator <<(tag <ostream> os, set <T> const& s){ vector <T> v; for (auto i: s) v.push_back(i); os.get()<<"["; for (int i=0; i<v.size(); i++) if (i!=v.size()-1) os.get()<<v[i]<<", "; else os.get()<<v[i]; return os.get()<<"]", os; }


void solve(){
    int n; 
    cin >> n;
    string s; cin >> s;
    vector<vector<ll>> dp(n, vector<ll>(10, 0));
    dp[0][s[0] - '0']++;
    for(int i = 1; i < n; i++){
        if(s[i] == '0'){
            dp[i][0] = 1;

            dp[i][2] = dp[i - 1][4] + dp[i - 1][8];
            dp[i][3] = dp[i - 1][0] + dp[i - 1][2] + dp[i - 1][5];
            
            dp[i][4] = dp[i - 1][1] + dp[i - 1][7];
            dp[i][5] = dp[i - 1][6];

            dp[i][8] = dp[i - 1][3];
            // dp[i][0] = 1 + dp[i - 1][2];
            // dp[i][1] = dp[i - 1][0] + dp[i - 1][3];

            // dp[i][2] = dp[i - 1][1] + dp[i - 1][4];
            // dp[i][3] = dp[i - 1][5];
        } else {
            dp[i][1] = 1;

            dp[i][2] = dp[i - 1][1] + dp[i - 1][3] + dp[i - 1][7];
            dp[i][3] = dp[i - 1][6] + dp[i - 1][8];
            
            dp[i][6] = dp[i - 1][0] + dp[i - 1][5];
            dp[i][7] = dp[i - 1][4];

            dp[i][8] = dp[i - 1][2];

            // dp[i][0] = dp[i - 1][1] + dp[i - 1][4];
            // dp[i][1] = 1 + dp[i - 1][5];

            // dp[i][4] = dp[i - 1][2];
            // dp[i][5] = dp[i - 1][0] + dp[i - 1][3];
        }
    }
    ll ans = 0;
    for(int i = 0; i < n; i++){
        // printf("%d:  %lld  %lld  ||  %lld  %lld  |  %lld %lld\n", i, dp[i][0], dp[i][1], dp[i][2], dp[i][3], dp[i][4], dp[i][5]);
        ans += dp[i][0] + dp[i][1] + dp[i][2] + dp[i][3];
    }
    cout << ans << "\n";
}

 
int32_t main(){
    BOOST;
 
    int q = 1; cin >> q;
    while(q--){
        solve();
    }
    return 0;
}
