// This file was generated by Clank
#include<bits/stdc++.h>
#define st first
#define nd second
#define all(x) x.begin(), x.end()
#define BOOST cin.tie(NULL); ios_base::sync_with_stdio(false);
 
#define int ll
typedef long long ll;

using namespace std;
template <typename T> struct tag:reference_wrapper <T>{ using reference_wrapper <T>::reference_wrapper; };
template <typename T1, typename T2> static inline tag <ostream> operator<<(tag <ostream> os, pair<T1, T2> const& p){ return os.get()<<"{"<<p.first<<", "<<p.second<<"}", os;}
template <typename Other> static inline tag <ostream> operator<<(tag <ostream> os, Other const& o){ os.get()<<o; return os; }
template <typename T> static inline tag <ostream> operator <<(tag <ostream> os, vector <T> const& v){ os.get()<<"["; for (int i=0; i<v.size(); i++) if (i!=v.size()-1) os.get()<<v[i]<<", "; else os.get()<<v[i]; return os.get()<<"]", os; }
template <typename T> static inline tag <ostream> operator <<(tag <ostream> os, set <T> const& s){ vector <T> v; for (auto i: s) v.push_back(i); os.get()<<"["; for (int i=0; i<v.size(); i++) if (i!=v.size()-1) os.get()<<v[i]<<", "; else os.get()<<v[i]; return os.get()<<"]", os; }


void solve(){
    int n; 
    cin >> n;
    vector<int> a(n * 2 + 1);
    vector<pair<int,int>> wh(n + 1);
    for(int i = 1; i <= 2 * n; i++){
        cin >> a[i];
        if(wh[a[i]].st == 0) wh[a[i]].st = i;
        else wh[a[i]].nd = i;
    }
    vector<ll> score(2 * n + 1);
    score[0] = 0;
    for(int i = 1; i <= 2 * n; i++){
        if(wh[a[i]].st == i){
            score[i] = score[i - 1] + 1;
        } else {
            score[i] = max(score[wh[a[i]].st - 1] + (wh[a[i]].nd - wh[a[i]].st + 1LL) * (wh[a[i]].nd - wh[a[i]].st + 1LL), score[i - 1] + 1);
        }
    }
    cout << score[2 * n] << "\n";
}

 
int32_t main(){
    BOOST;
 
    int q = 1; cin >> q;
    while(q--){
        solve();
    }
    return 0;
}
