// This file was generated by Clank
#include<bits/stdc++.h>
#define st first
#define nd second
#define all(x) x.begin(), x.end()
#define BOOST cin.tie(NULL); ios_base::sync_with_stdio(false);
 
// #define int ll
typedef long long ll;

using namespace std;
template <typename T> struct tag:reference_wrapper <T>{ using reference_wrapper <T>::reference_wrapper; };
template <typename T1, typename T2> static inline tag <ostream> operator<<(tag <ostream> os, pair<T1, T2> const& p){ return os.get()<<"{"<<p.first<<", "<<p.second<<"}", os;}
template <typename Other> static inline tag <ostream> operator<<(tag <ostream> os, Other const& o){ os.get()<<o; return os; }
template <typename T> static inline tag <ostream> operator <<(tag <ostream> os, vector <T> const& v){ os.get()<<"["; for (int i=0; i<v.size(); i++) if (i!=v.size()-1) os.get()<<v[i]<<", "; else os.get()<<v[i]; return os.get()<<"]", os; }
template <typename T> static inline tag <ostream> operator <<(tag <ostream> os, set <T> const& s){ vector <T> v; for (auto i: s) v.push_back(i); os.get()<<"["; for (int i=0; i<v.size(); i++) if (i!=v.size()-1) os.get()<<v[i]<<", "; else os.get()<<v[i]; return os.get()<<"]", os; }

void solve2(int n, int p00, int p01, int p10, int p11){
    if(p01 >= p10){
        p01 -= p10;
        p10 = 0;
    } else {
        p10 -= p01;
        p01 = 0;
    }
    if(p00 + p11 >= p10 + p01){
        cout << "YES\n";
    } else {
        cout << "NO\n";
    }
}

void solve(){
    int n, q; cin >> n >> q;
    string a, b;
    cin >> a >> b;
    vector<int> pref[4]; // 00, 01, 10, 11;
    pref[0].assign(n + 1, 0);
    pref[1].assign(n + 1, 0);
    pref[2].assign(n + 1, 0);
    pref[3].assign(n + 1, 0);
    for(int i = 1; i <= n; i++){
        pref[0][i] = pref[0][i - 1];
        pref[1][i] = pref[1][i - 1];
        pref[2][i] = pref[2][i - 1];
        pref[3][i] = pref[3][i - 1];
        if(a[i - 1] == '0'){
            if(b[i - 1] == '0'){
                pref[0][i]++;
            } else {
                pref[1][i]++;
            }
        } else {
            if(b[i - 1] == '0'){
                pref[2][i]++;
            } else {
                pref[3][i]++;
            }
        }
    }
    int l, r;
    while(q--){
        cin >> l >> r;
        solve2(r - l + 1, pref[0][r] - pref[0][l - 1], pref[1][r] - pref[1][l - 1], pref[2][r] - pref[2][l - 1], pref[3][r] - pref[3][l - 1]);
    }
}

 
int32_t main(){
    BOOST;
 
    int q = 1; cin >> q;
    while(q--){
        solve();
    }
    return 0;
}
