// This file was generated by Clank
#include<bits/stdc++.h>
#define st first
#define nd second
#define all(x) x.begin(), x.end()
#define BOOST cin.tie(NULL); ios_base::sync_with_stdio(false);
 
// #define int ll
typedef long long ll;

using namespace std;
template <typename T> struct tag:reference_wrapper <T>{ using reference_wrapper <T>::reference_wrapper; };
template <typename T1, typename T2> static inline tag <ostream> operator<<(tag <ostream> os, pair<T1, T2> const& p){ return os.get()<<"{"<<p.first<<", "<<p.second<<"}", os;}
template <typename Other> static inline tag <ostream> operator<<(tag <ostream> os, Other const& o){ os.get()<<o; return os; }
template <typename T> static inline tag <ostream> operator <<(tag <ostream> os, vector <T> const& v){ os.get()<<"["; for (int i=0; i<v.size(); i++) if (i!=v.size()-1) os.get()<<v[i]<<", "; else os.get()<<v[i]; return os.get()<<"]", os; }
template <typename T> static inline tag <ostream> operator <<(tag <ostream> os, set <T> const& s){ vector <T> v; for (auto i: s) v.push_back(i); os.get()<<"["; for (int i=0; i<v.size(); i++) if (i!=v.size()-1) os.get()<<v[i]<<", "; else os.get()<<v[i]; return os.get()<<"]", os; }


void solve(){
    int n, m; 
    cin >> n >> m;
    vector<int> a(n), b(m);
    vector<pair<int,int>> ab(n + m);
    for(int i = 0; i < n; i++){
        cin >> a[i];
        ab[i] = {a[i], 1};
    }
    for(int i = 0; i < m; i++){
        cin >> b[i];
        ab[i + n] = {b[i], -1};
    }
    if(n < 2 * m){
        cout << "NO\n";
        return;
    }
    sort(all(a));
    sort(all(b));
    sort(all(ab));
    // int ctra, ctrb;
    int bal = 0;
    for(int i = 0; i < n + m; i++){
        bal += ab[i].nd;
        if(bal < 0){
            cout << "NO\n";
            return;
        }
    }
    bal = 0;
    for(int i = 1; i <= n + m; i++){
        bal += ab[n + m - i].nd;
        if(bal < 0){
            cout << "NO\n";
            return;
        }
    }
    cout << "YES\n";
}

 
int32_t main(){
    BOOST;
 
    int q = 1; cin >> q;
    while(q--){
        solve();
    }
    return 0;
}
