// This file was generated by Clank
#include<bits/stdc++.h>
#define st first
#define nd second
#define all(x) x.begin(), x.end()
#define BOOST cin.tie(NULL); ios_base::sync_with_stdio(false);
 
#define int ll
typedef long long ll;

using namespace std;
template <typename T> struct tag:reference_wrapper <T>{ using reference_wrapper <T>::reference_wrapper; };
template <typename T1, typename T2> static inline tag <ostream> operator<<(tag <ostream> os, pair<T1, T2> const& p){ return os.get()<<"{"<<p.first<<", "<<p.second<<"}", os;}
template <typename Other> static inline tag <ostream> operator<<(tag <ostream> os, Other const& o){ os.get()<<o; return os; }
template <typename T> static inline tag <ostream> operator <<(tag <ostream> os, vector <T> const& v){ os.get()<<"["; for (int i=0; i<v.size(); i++) if (i!=v.size()-1) os.get()<<v[i]<<", "; else os.get()<<v[i]; return os.get()<<"]", os; }
template <typename T> static inline tag <ostream> operator <<(tag <ostream> os, set <T> const& s){ vector <T> v; for (auto i: s) v.push_back(i); os.get()<<"["; for (int i=0; i<v.size(); i++) if (i!=v.size()-1) os.get()<<v[i]<<", "; else os.get()<<v[i]; return os.get()<<"]", os; }

bool check(int n, int m, ll psum, int len, vector<int> &p, vector<int> &r, vector<ll> &prefr){
    // cout << "CHECK: " << psum << " " << len << "\n";
    if(psum <= 0) return false;

    int currlen = 0;
    int lptr = 0, rptr = 1;
    while(p[rptr] - 1 < len) rptr++;
    for(; rptr <= 2 * m; rptr++){
        while(lptr + 1 < rptr && p[rptr] - 1 - p[lptr + 1] >= len){
            lptr++;
        }
        // cout << lptr << " - " << rptr << "\n";
        if(p[rptr] - 1 - p[lptr] >= len){
            // cout << "ok1 " << prefr[rptr - 1] - prefr[lptr] <<  "\n";
            if(prefr[rptr - 1] - prefr[lptr] < psum){
                // cout << "ok2" << "\n";
                return true;
            }
        }
    }
    return false;
}

void solve(){
    int n, m, d; 
    cin >> n >> m >> d;
    vector<int> p(2 * m + 1), r(2 * m + 1), prefr(2 * m + 1);
    p[0] = -1;
    for(int i = 1; i <= m; i++){
        cin >> p[i] >> r[i];
    }
    for(int i = 1; i <= m; i++){
        p[i + m] = n + p[i];
        r[i + m] = r[i];
    }
    for(int i = 1; i <= 2 * m; i++){
        prefr[i] = prefr[i - 1] + r[i];
    }

    // cout << p << "\n";
    // cout << r << "\n";
    // cout << prefr << "\n";

    ll sum = 0;
    for(int i = 1; i <= m; i++){
        sum += r[i];
        if(check(n,m, sum - d, p[i] + 1, p, r, prefr)){
            cout << "YES\n";
            return;
        }
    }
    cout << "NO\n";
    return;
}

 
int32_t main(){
    BOOST;
 
    int q = 1; cin >> q;
    while(q--){
        solve();
    }
    return 0;
}
