// This file was generated by Clank
#include<bits/stdc++.h>
#define st first
#define nd second
#define all(x) x.begin(), x.end()
#define BOOST cin.tie(NULL); ios_base::sync_with_stdio(false);
 
// #define int ll
typedef long long ll;

using namespace std;
template <typename T> struct tag:reference_wrapper <T>{ using reference_wrapper <T>::reference_wrapper; };
template <typename T1, typename T2> static inline tag <ostream> operator<<(tag <ostream> os, pair<T1, T2> const& p){ return os.get()<<"{"<<p.first<<", "<<p.second<<"}", os;}
template <typename Other> static inline tag <ostream> operator<<(tag <ostream> os, Other const& o){ os.get()<<o; return os; }
template <typename T> static inline tag <ostream> operator <<(tag <ostream> os, vector <T> const& v){ os.get()<<"["; for (int i=0; i<v.size(); i++) if (i!=v.size()-1) os.get()<<v[i]<<", "; else os.get()<<v[i]; return os.get()<<"]", os; }
template <typename T> static inline tag <ostream> operator <<(tag <ostream> os, set <T> const& s){ vector <T> v; for (auto i: s) v.push_back(i); os.get()<<"["; for (int i=0; i<v.size(); i++) if (i!=v.size()-1) os.get()<<v[i]<<", "; else os.get()<<v[i]; return os.get()<<"]", os; }

vector<int> pref;

vector<int> solve2(int jumpctr, int diff){
    vector<int> ans(jumpctr + 10, 0);
    int xctr = 0;
    int lenctr = 0;
    while(xctr * xctr - pref[max(0, lenctr - jumpctr - 1)] < diff){
        xctr++;
        lenctr += 2;
    }
    int curr_diff = (xctr * xctr - pref[max(0, lenctr - jumpctr - 1)]);
    if(lenctr - 1 > jumpctr && (curr_diff&1) != (diff&1)) assert(false);
    for(int i = xctr; i < jumpctr && i < lenctr; i++){
        ans[i] = 1;
    }
    // if(lenctr - 1 <= jumpctr && (jumpctr - (lenctr - 1)) % 4 >= 2) assert(false);
    for(int i = lenctr; i < jumpctr; i += 4){
        ans[i] = 0;
        ans[i + 1] = 1;
        ans[i + 2] = 1;
        ans[i + 3] = 0;
    }
    if(ans[jumpctr - 2] == 0 || ans[jumpctr - 1] == 0) curr_diff++;
    // if(abs(curr_diff - diff) <= 1) return ans;
    while(curr_diff - diff >= 2){
        swap(ans[xctr - 1], ans[xctr]);
        xctr--;
        curr_diff -= 2;
    }
    return ans;
}

void solve(){
    int statx, staty; cin >> statx >> staty;
    int tdiag = 0, tjump = 1, jumpctr = 0;
    while(tdiag + tjump <= statx + staty){
        tdiag += tjump;
        tjump++;
        jumpctr++;
    }
    // cout << tdiag << " - " << tjump << " " << jumpctr << "\n";
    int tmp = statx + staty - tdiag;
    int destx = statx - tmp / 2, desty = staty - (tmp + 1)/2;
    if(destx < 0){
        desty += destx;
        destx = 0;
    }
    if(desty < 0){
        destx += desty;
        desty = 0;
    }
    // cout << destx << " " << desty << " " << abs(desty - destx) << "\n";
    int swp = 0;
    if(desty > destx){
        swp = 1;
        swap(desty, destx);
    }
    int diff = destx - desty;
    vector<int> ans = solve2(jumpctr, diff);
    for(int i = 0; i < jumpctr; i++){
        if(ans[i] ^ swp){
            cout << "Y";
        } else {
            cout << "X";
        }
    }
    cout << "\n";
    
}

 
int32_t main(){
    BOOST;
    
    pref.resize(20010, 0);
    for(int i = 1; i <= 20005; i++){
        pref[i] = pref[i - 1] + i;
    }

    int q = 1; cin >> q;
    while(q--){
        solve();
    }
    return 0;
}
/*
XXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXYYYYYYYYYY YYYYYYX
XXXXXXYXXXYYYYYYYYXYYXXYYXX
*/
