// This file was generated by Clank
#include<bits/stdc++.h>
#define st first
#define nd second
#define all(x) x.begin(), x.end()
#define BOOST cin.tie(NULL); ios_base::sync_with_stdio(false);
 
#define int ll
typedef long long ll;

using namespace std;
template <typename T> struct tag:reference_wrapper <T>{ using reference_wrapper <T>::reference_wrapper; };
template <typename T1, typename T2> static inline tag <ostream> operator<<(tag <ostream> os, pair<T1, T2> const& p){ return os.get()<<"{"<<p.first<<", "<<p.second<<"}", os;}
template <typename Other> static inline tag <ostream> operator<<(tag <ostream> os, Other const& o){ os.get()<<o; return os; }
template <typename T> static inline tag <ostream> operator <<(tag <ostream> os, vector <T> const& v){ os.get()<<"["; for (int i=0; i<v.size(); i++) if (i!=v.size()-1) os.get()<<v[i]<<", "; else os.get()<<v[i]; return os.get()<<"]", os; }
template <typename T> static inline tag <ostream> operator <<(tag <ostream> os, set <T> const& s){ vector <T> v; for (auto i: s) v.push_back(i); os.get()<<"["; for (int i=0; i<v.size(); i++) if (i!=v.size()-1) os.get()<<v[i]<<", "; else os.get()<<v[i]; return os.get()<<"]", os; }


void solve(){
    int n, m, x, y; 
    cin >> n >> m >> x >> y;
    vector<int> a(x), b(y);
    for(int i = 0; i < x; i++){
        cin >> a[i];
    }
    for(int i = 0; i < y; i++){
        cin >> b[i];
    }
    int la = n - 1, lb = m - 1, lx = 1;
    int skip = 0;
    ll ans = 0;
    int ptra = x - 1;
    int ptrb = y - 1;
    while(la + lb + lx > skip && ptra >= 0 && ptrb >= 0 && ((la > 0 && lb > 0) || a[ptra] == b[ptrb])){
        if(a[ptra] == b[ptrb]){
            skip++;
            ans += a[ptra];
            ptra--;
            ptrb--;
            continue;
        }
        if(a[ptra] > b[ptrb]){
            ans += a[ptra];
            la--;
            ptra--;
        } else {
            ans += b[ptrb];
            lb--;
            ptrb--;
        }
    }
    // cout << ans << " " << skip << " " << "\n";
    if(la + lb + lx == skip){
        cout << ans << "\n";
        return;
    }
    if(ptra < 0){
        skip = max(0LL, skip - la);
        while(ptrb >= 0 && lb + lx > skip){
            ans += b[ptrb];
            ptrb--;
            lb--;
        }
        cout << ans << "\n";
        return;
    }
    if(ptrb < 0){
        skip = max(0LL, skip - lb);
        while(ptra >= 0 && la + lx > skip){
            ans += a[ptra];
            ptra--;
            la--;
        }
        cout << ans << "\n";
        return;
    }
    if(la == 0){
        // if(a[ptra] > b[ptrb]){
        //     ans += a[ptra];
        //     lx = 0;
        // }
        while(ptrb >= 0 && lb + lx > skip){
            if(ptra >= 0){
                if(lx == 1 && a[ptra] > b[ptrb]){
                    ans += a[ptra];
                    lx = 0;
                    continue;
                }
                if(a[ptra] == b[ptrb]) ptra--;
            }
            ans += b[ptrb];
            ptrb--;
            lb--;
        }
        if(ptrb < 0 && lb + lx > skip && lx == 1 && ptra >= 0){
            ans += a[ptra];
        }
        cout << ans << "\n";
        return;
    }
    if(lb == 0){
        // if(a[ptra] < b[ptrb]){
        //     ans += b[ptrb];
        //     lx = 0;
        // }
        while(ptra >= 0 && la + lx > skip){
            if(ptrb >= 0){
                if(lx == 1 && a[ptra] < b[ptrb]){
                    ans += b[ptrb];
                    lx = 0;
                    continue;
                }
                if(a[ptra] == b[ptrb]) ptrb--;
            }
            ans += a[ptra];
            ptra--;
            la--;
        }
        if(ptra < 0 && la + lx > skip && lx == 1 && ptrb >= 0){
            ans += b[ptrb];
        }
        cout << ans << "\n";
        return;
    }
}

 
int32_t main(){
    BOOST;
 
    int q = 1; cin >> q;
    while(q--){
        solve();
    }
    return 0;
}
