// This file was generated by Clank
#include<bits/stdc++.h>
#define st first
#define nd second
#define all(x) x.begin(), x.end()
#define BOOST cin.tie(NULL); ios_base::sync_with_stdio(false);
 
#define int ll
typedef long long ll;

using namespace std;
template <typename T> struct tag:reference_wrapper <T>{ using reference_wrapper <T>::reference_wrapper; };
template <typename T1, typename T2> static inline tag <ostream> operator<<(tag <ostream> os, pair<T1, T2> const& p){ return os.get()<<"{"<<p.first<<", "<<p.second<<"}", os;}
template <typename Other> static inline tag <ostream> operator<<(tag <ostream> os, Other const& o){ os.get()<<o; return os; }
template <typename T> static inline tag <ostream> operator <<(tag <ostream> os, vector <T> const& v){ os.get()<<"["; for (int i=0; i<v.size(); i++) if (i!=v.size()-1) os.get()<<v[i]<<", "; else os.get()<<v[i]; return os.get()<<"]", os; }
template <typename T> static inline tag <ostream> operator <<(tag <ostream> os, set <T> const& s){ vector <T> v; for (auto i: s) v.push_back(i); os.get()<<"["; for (int i=0; i<v.size(); i++) if (i!=v.size()-1) os.get()<<v[i]<<", "; else os.get()<<v[i]; return os.get()<<"]", os; }

ll mod = 998244353;

int pot(int a, int k){
    if(k == 0) return 1;
    ll tmp = pot(a, k / 2);
    if(k&1){
        return (((tmp * tmp) % mod) * a) % mod;
    }
    return (tmp * tmp) % mod;
}

int revmod(int x){
    return pot(x, mod - 2);
}

int newt(int n, int k){
    if(k < 0) return 1;
    // cout << "newt: " << n << " po " << k << "\n";
    ll licz = 1, mian = 1;
    int lim1 = max(n - k, k), lim2 = min(n - k, k);
    for(int i = lim1 + 1; i <= n; i++){
        licz = (licz * i) % mod;
    }
    for(int i = 2; i <= lim2; i++){
        mian = (mian * i) % mod;
    }
    // cout << licz << " - " << mian << ",  " << revmod(mian) << "\n";
    return (licz * revmod(mian)) % mod;
}

void solve(){
    int n; 
    cin >> n;
    string s; cin >> s;
    int ctr = 1;
    int m0 = 0, m1 = 0;
    int b0 = 0, b1 = 0;
    for(int i = 1; i < n; i++){
        if(s[i - 1] != s[i]){
            if(s[i - 1] == '0'){
                b0++;
                m0 += ctr - 1;
            } else {
                b1++;
                m1 += ctr - 1;
            }
            ctr = 1;
        } else {
            ctr++;
        }
    }
    if(s[n - 1] == '0'){
        b0++;
        m0 += ctr - 1;
    } else {
        b1++;
        m1 += ctr - 1;
    }

    cout << (newt(b0 - 1 + m0, b0 - 1) * newt(b1 - 1 + m1, b1 - 1)) % mod << "\n";
}

 
int32_t main(){
    BOOST;
    // cout << pot(2, 10) << "\n";
 
    int q = 1; cin >> q;
    while(q--){
        solve();
    }
    return 0;
}
