// This file was generated by Clank
#include<bits/stdc++.h>
#define st first
#define nd second
#define all(x) x.begin(), x.end()
#define BOOST cin.tie(NULL); ios_base::sync_with_stdio(false);
 
// #define int ll
typedef long long ll;

using namespace std;
template <typename T> struct tag:reference_wrapper <T>{ using reference_wrapper <T>::reference_wrapper; };
template <typename T1, typename T2> static inline tag <ostream> operator<<(tag <ostream> os, pair<T1, T2> const& p){ return os.get()<<"{"<<p.first<<", "<<p.second<<"}", os;}
template <typename Other> static inline tag <ostream> operator<<(tag <ostream> os, Other const& o){ os.get()<<o; return os; }
template <typename T> static inline tag <ostream> operator <<(tag <ostream> os, vector <T> const& v){ os.get()<<"["; for (int i=0; i<v.size(); i++) if (i!=v.size()-1) os.get()<<v[i]<<", "; else os.get()<<v[i]; return os.get()<<"]", os; }
template <typename T> static inline tag <ostream> operator <<(tag <ostream> os, set <T> const& s){ vector <T> v; for (auto i: s) v.push_back(i); os.get()<<"["; for (int i=0; i<v.size(); i++) if (i!=v.size()-1) os.get()<<v[i]<<", "; else os.get()<<v[i]; return os.get()<<"]", os; }

bool check(string s, string &start){
    // cout << start << "\n";
    if(s[0] == '?') s[0] = start[0];
    if(s[1] == '?') s[1] = start[1];
    // cout << s << " " << start << '\n';
    if(s[0] != start[0] || s[1] != start[1]) return false;
    // cout << "ok1\n";
    int curr = s[0] + s[1];
    int next;
    for(int i = 2; i < s.size(); i++){
        if(s[i] == '?'){
            if(s[i - 1] + '0' == curr){
                s[i] = '1';
            } else {
                s[i] = '0';
            }
        } 
        next = s[i] + s[i - 1];
        if(next == curr) return false;
        curr = next;
    }
    return true;
}

void solve(){
    int n; cin >> n;
    string s; cin >> s;
    vector<string> spos = {"00", "10", "01", "11"};
    int ans = 0;
    for(int i = 0; i < 4; i++){
        if(check(s, spos[i])) ans++;
    }
    cout << ans << "\n";
}

 
int32_t main(){
    BOOST;
 
    int q = 1; cin >> q;
    while(q--){
        solve();
    }
    return 0;
}
