// This file was generated by Clank
#include<bits/stdc++.h>
#define st first
#define nd second
#define all(x) x.begin(), x.end()
#define BOOST cin.tie(NULL); ios_base::sync_with_stdio(false);
 
// #define int ll
typedef long long ll;

using namespace std;
template <typename T> struct tag:reference_wrapper <T>{ using reference_wrapper <T>::reference_wrapper; };
template <typename T1, typename T2> static inline tag <ostream> operator<<(tag <ostream> os, pair<T1, T2> const& p){ return os.get()<<"{"<<p.first<<", "<<p.second<<"}", os;}
template <typename Other> static inline tag <ostream> operator<<(tag <ostream> os, Other const& o){ os.get()<<o; return os; }
template <typename T> static inline tag <ostream> operator <<(tag <ostream> os, vector <T> const& v){ os.get()<<"["; for (int i=0; i<v.size(); i++) if (i!=v.size()-1) os.get()<<v[i]<<", "; else os.get()<<v[i]; return os.get()<<"]", os; }
template <typename T> static inline tag <ostream> operator <<(tag <ostream> os, set <T> const& s){ vector <T> v; for (auto i: s) v.push_back(i); os.get()<<"["; for (int i=0; i<v.size(); i++) if (i!=v.size()-1) os.get()<<v[i]<<", "; else os.get()<<v[i]; return os.get()<<"]", os; }


void solve(){
    int n, m; 
    cin >> n >> m;
    vector<int> a(n);
    vector<int> b(m);

    for(int i = 0; i < n; i++){
        cin >> a[i];
    }
    for(int i = 0; i < m; i++){
        cin >> b[i];
    }
    int ptr1 = 0, ptr2 = 0;
    a.push_back(1);
    b.push_back(1);
    while(ptr1 != n && ptr2 != m){
        if(b[ptr2] == b[ptr2 + 1]){
            b[ptr2]--;
            ptr2++;
            a[ptr1]--;
            if(a[ptr1] < a[ptr1 + 1]){
                ptr1++;
            }
            continue;
        }
        if(a[ptr1] == a[ptr1 + 1]){
            b[ptr2]--;
            a[ptr1]--;
            ptr1++;
            continue;
        }
        int tmp = min(a[ptr1] - a[ptr1 + 1], b[ptr2] - b[ptr2 + 1]);
        a[ptr1] -= tmp;
        b[ptr2] -= tmp;
    }
    if(ptr2 == m){
        cout << 1 << "\n";
        return;
    }
    cout << 2 << "\n";
}

 
int32_t main(){
    BOOST;
 
    int q = 1; cin >> q;
    while(q--){
        solve();
    }
    return 0;
}
