// This file was generated by Clank
#include<bits/stdc++.h>
#define st first
#define nd second
#define all(x) x.begin(), x.end()
#define BOOST cin.tie(NULL); ios_base::sync_with_stdio(false);
 
// #define int ll
typedef long long ll;

using namespace std;
template <typename T> struct tag:reference_wrapper <T>{ using reference_wrapper <T>::reference_wrapper; };
template <typename T1, typename T2> static inline tag <ostream> operator<<(tag <ostream> os, pair<T1, T2> const& p){ return os.get()<<"{"<<p.first<<", "<<p.second<<"}", os;}
template <typename Other> static inline tag <ostream> operator<<(tag <ostream> os, Other const& o){ os.get()<<o; return os; }
template <typename T> static inline tag <ostream> operator <<(tag <ostream> os, vector <T> const& v){ os.get()<<"["; for (int i=0; i<v.size(); i++) if (i!=v.size()-1) os.get()<<v[i]<<", "; else os.get()<<v[i]; return os.get()<<"]", os; }
template <typename T> static inline tag <ostream> operator <<(tag <ostream> os, set <T> const& s){ vector <T> v; for (auto i: s) v.push_back(i); os.get()<<"["; for (int i=0; i<v.size(); i++) if (i!=v.size()-1) os.get()<<v[i]<<", "; else os.get()<<v[i]; return os.get()<<"]", os; }

void dfs(int curr, vector<vector<int>> &g, vector<int> &p, vector<int> &d){
    for(int i : g[curr]){
        if(i != p[curr]){
            d[i] = d[curr] + 1;
            dfs(i, g, p, d);
        }
    }
}

void solve(){
    int n; 
    cin >> n;
    vector<int> a(n);
    vector<vector<int>> g(n + 1);
    vector<int> p(n + 1, 0);
    vector<int> d(n + 1, 0);
    p[1] = 1;
    for(int i = 2; i <= n; i++){
        cin >> p[i];
        g[p[i]].push_back(i);
        g[i].push_back(p[i]);
    }
    dfs(1,g,p,d);
    int m;
    cin >> m;
    int tmp;
    vector<pair<int,int>> ans;
    for(int i = 0; i < m; i++){
        cin >> tmp;
        ans.push_back({d[tmp], tmp});
    }
    sort(all(ans));
    cout << m - 1 << " ";
    for(int i = 1; i < m; i++){
        cout << ans[i].nd << " ";
    }
    cout << "\n";
}

 
int32_t main(){
    BOOST;
 
    int q = 1; cin >> q;
    while(q--){
        solve();
    }
    return 0;
}
