// This file was generated by Clank
#include<bits/stdc++.h>
#define st first
#define nd second
#define all(x) x.begin(), x.end()
#define BOOST cin.tie(NULL); ios_base::sync_with_stdio(false);
 
// #define int ll
typedef long long ll;

using namespace std;
template <typename T> struct tag:reference_wrapper <T>{ using reference_wrapper <T>::reference_wrapper; };
template <typename T1, typename T2> static inline tag <ostream> operator<<(tag <ostream> os, pair<T1, T2> const& p){ return os.get()<<"{"<<p.first<<", "<<p.second<<"}", os;}
template <typename Other> static inline tag <ostream> operator<<(tag <ostream> os, Other const& o){ os.get()<<o; return os; }
template <typename T> static inline tag <ostream> operator <<(tag <ostream> os, vector <T> const& v){ os.get()<<"["; for (int i=0; i<v.size(); i++) if (i!=v.size()-1) os.get()<<v[i]<<", "; else os.get()<<v[i]; return os.get()<<"]", os; }
template <typename T> static inline tag <ostream> operator <<(tag <ostream> os, set <T> const& s){ vector <T> v; for (auto i: s) v.push_back(i); os.get()<<"["; for (int i=0; i<v.size(); i++) if (i!=v.size()-1) os.get()<<v[i]<<", "; else os.get()<<v[i]; return os.get()<<"]", os; }

ll allc;
vector<ll> divs;
vector<pair<ll,ll>> block;
vector<ll> pref;

// struct el{
//     ll h;   // from the start
//     ll w;   // curr width
//     ll p;   // prefix sum from up;
// };

void prep(ll s){
    divs.clear();
    divs.push_back(0);
    for(ll i = 1; i * i <= s; i++){
        if(s % i == 0){
            divs.push_back(i);
        }
    }
    for(int i = (int)divs.size() - 1; i > 0; i--){
        if(s / divs[i] != divs[i]) divs.push_back(s / divs[i]);
    }
    reverse(all(divs));
    // vector<ll> ph(divs.size(), 0); // to samo co divs;
    block.clear();
    pref.assign(divs.size() + 10, 0);
    for(int i = 0; i < (int)divs.size() - 1; i++){
        block.push_back({divs[i] - divs[i + 1], s / divs[i]});
        pref[i + 1] = pref[i] + block.back().st * block.back().nd;
    }

}

bool ins(ll x, ll y, ll s){
    int po = 0, ko = (int)divs.size() - 1, sr;
    while(po + 1 < ko){
        sr = (po + ko) / 2;
        if(divs[sr] >= x){
            po = sr;
        } else {
            ko = sr;
        }
    }
    // cout << po << " po\n";
    if(s / divs[po] >= y) return true;
    return false;
}

ll cut(ll h, ll s){
    int po = 0, ko = (int)divs.size() - 1, sr;
    while(po + 1 < ko){
        sr = (po + ko) / 2;
        if(divs[sr] >= h){
            po = sr;
        } else {
            ko = sr;
        }
    }
    // cout << po << " po2\n";

    return pref[po] + (divs[po] - h) * block[po].nd;
}

void solve2(ll x, ll y, ll s){
    if(ins(x, y, s)){
        cout << x * y << "\n";
        return;
    }
    cout << allc - cut(x, s) - cut(y, s) << "\n";
}

void solve(){
    ll s, x, y;
    int q; 
    cin >> s >> q;
    prep(s);
    allc = pref[(int)divs.size() - 1];
    // cout << divs << "\n";
    // cout << block << "\n";
    // cout << pref << "\n";
    while(q--){
        cin >> x >> y;
        solve2(x, y, s);
    }
}

 
int32_t main(){
    BOOST;
 
    int q = 1; cin >> q;
    while(q--){
        solve();
    }
    return 0;
}
