// This file was generated by Clank
#include<bits/stdc++.h>
#define st first
#define nd second
#define all(x) x.begin(), x.end()
#define BOOST cin.tie(NULL); ios_base::sync_with_stdio(false);
 
#define int ll
typedef long long ll;

using namespace std;
template <typename T> struct tag:reference_wrapper <T>{ using reference_wrapper <T>::reference_wrapper; };
template <typename T1, typename T2> static inline tag <ostream> operator<<(tag <ostream> os, pair<T1, T2> const& p){ return os.get()<<"{"<<p.first<<", "<<p.second<<"}", os;}
template <typename Other> static inline tag <ostream> operator<<(tag <ostream> os, Other const& o){ os.get()<<o; return os; }
template <typename T> static inline tag <ostream> operator <<(tag <ostream> os, vector <T> const& v){ os.get()<<"["; for (int i=0; i<v.size(); i++) if (i!=v.size()-1) os.get()<<v[i]<<", "; else os.get()<<v[i]; return os.get()<<"]", os; }
template <typename T> static inline tag <ostream> operator <<(tag <ostream> os, set <T> const& s){ vector <T> v; for (auto i: s) v.push_back(i); os.get()<<"["; for (int i=0; i<v.size(); i++) if (i!=v.size()-1) os.get()<<v[i]<<", "; else os.get()<<v[i]; return os.get()<<"]", os; }

pair<pair<ll,int>, pair<ll,int>> check_next(int idx, vector<int> &p, vector<int> &r, vector<int> &h, vector<int> &m){
    pair<pair<ll,int>, pair<ll,int>> ans = {{0,-1},{0,0}};
    ll diff = 0;
    ll max_diff = 0;
    for(int i = h[idx]; i < m[idx]; i++){
        diff -= p[i];
        max_diff = min(max_diff, diff);
        diff += r[i];
        if(diff >= 0){
            ans.st.st = max_diff;
            ans.st.nd = idx;
            ans.nd.st = diff;
            ans.nd.nd = i - h[idx] + 1;
            break;
        }
    }
    return ans;
}

void solve(){
    int n;
    ll kasa; 
    cin >> n >> kasa;
    vector<vector<int>> p(n);
    vector<vector<int>> r(n);
    vector<int> m(n, 0);
    vector<int> h(n, 0);
    for(int i = 0; i < n; i++){
        cin >> m[i];
        p[i].resize(m[i]);
        r[i].resize(m[i]);
        for(int j = 0 ; j < m[i] ; j++){
            cin >> p[i][j];
        }
        for(int j = 0 ; j < m[i] ; j++){
            cin >> r[i][j];
        }
    }
    priority_queue<pair<pair<ll,int>,pair<ll,int>>> pq; // ile trzeba miec kasy, gdzie, ile sie zyskuje kasy, ile sie zyskuje pieter;
    pair<pair<ll,int>, pair<ll,int>> tmp;
    for(int i = 0; i < n; i++){
        tmp = check_next(i, p[i], r[i], h, m);
        // cout << tmp << "\n";
        if(tmp.st.nd == -1) continue; 
        pq.push(tmp);
    }
    while(!pq.empty()){
        tmp = pq.top();
        pq.pop();
        tmp.st.st *= -1;
        if(kasa >= tmp.st.st){
            h[tmp.st.nd] += tmp.nd.nd;
            kasa += tmp.nd.st;
            tmp = check_next(tmp.st.nd, p[tmp.st.nd], r[tmp.st.nd], h, m);
            // cout << tmp << "\n";

            if(tmp.st.nd == -1) continue; 
            pq.push(tmp);
        }
    }
    int ans = 0, idx_ans = 0;
    ll tkasa;
    for(int i = 0; i < n; i++){
        tkasa = kasa;
        while(h[i] != m[i] && p[i][h[i]] <= tkasa){
            tkasa += r[i][h[i]] - p[i][h[i]];
            h[i]++;
            // cout << tkasa << " t\n";
        }
        if(ans < h[i]){
            ans = h[i];
            idx_ans = i;
        }
    }
    cout << ans << " " << idx_ans + 1 << "\n";
}

 
int32_t main(){
    BOOST;
 
    int q = 1; cin >> q;
    while(q--){
        solve();
    }
    return 0;
}
