// Template generated by Clank
#include<bits/stdc++.h>
using namespace std;
#define st first
#define nd second
#define all(x) x.begin(), x.end()
#define BOOST cin.tie(NULL); ios_base::sync_with_stdio(false);
// #define int ll
typedef long long ll;

struct Node{
    int k, p;
    Node *l, *r;

    Node(int ik) : k(ik), p(rand()), l(NULL), r(NULL) {}
};

void split(Node *t, Node *&lt, Node *&rt, int split_key){
    if(!t){
        lt = NULL;
        rt = NULL;
    } else if(t->k <= split_key){
        split(t->r, t->r, rt, split_key);
        lt = t;
    } else {
        split(t->l, lt, t->l, split_key);
        rt = t;
    }
}

void merge(Node *&t, Node *lt, Node *rt){
    if(!lt){ t = rt; return;}
    if(!rt){ t = lt; return;}
    if(lt->p > rt->p){
        merge(lt->r, lt->r, rt);
        t = lt;
    } else {
        merge(rt->l, lt, rt->l);
        t = rt;
    }
}

void insert(Node *&t, Node *item){
    Node *l, *r;
    split(t, l, r, item->k);
    merge(l, l, item);
    merge(t, l, r);
}

void erase(Node *&t, int key){
    Node *l, *r;
    split(t, l, r, key);
    split(l, l, t, key - 1);
    merge(t, l, r);
}

void Union(Node *&t, Node *lt, Node *rt){
    if(!lt){ t = rt; return;}
    if(!rt){ t = lt; return;}
    Node *tmpl, *tmpr;
    if(lt->p > rt->p){
        split(rt, tmpl, tmpr, lt->k);
        Union(lt->l, lt->l, tmpl);
        Union(lt->r, lt->r, tmpr);
        t = lt;
    } else {
        split(lt, tmpl, tmpr, rt->k);
        Union(rt->l, tmpl, rt->l);
        Union(rt->r, tmpr, rt->r);
        t = rt;
    }
    // update(t);
}

void dfs(Node *t, vector<int> &ans, int col){
    if(!t) return;
    ans[t->k] = col;
    dfs(t->l, ans, col);
    dfs(t->r, ans, col);
}

void print_node(Node *t, int shift){
    for(int i = 0; i < shift; i++){
        cout << "    ";
    }
    if(!t){ cout << "NULL\n"; return; }
    cout << "( " << t->k << ", " << t->p << " ) \n";
}
void print_treap(Node *t, int shift){
    if(!t){
        print_node(t, shift);
        return;
    }
    print_treap(t->r, shift + 1);
    print_node(t, shift);
    print_treap(t->l, shift + 1);
}

void print_all(vector<Node*> ts, int max_col){
    for(int i = 1; i <= max_col; i++){
        cout << "====================== " <<  i << " ======================\n";
        print_treap(ts[i], 0);
    }
    cout << "===============================================================================================\n===============================================================================================\n";
}

int32_t main(){
    BOOST;
    srand(42);
    int n; cin >> n;
    int ai;
    vector<Node*> roots(101, NULL);
    Node *item;

    for(int i = 0; i < n; i++){
        cin >> ai;
        item = new Node(i);
        merge(roots[ai], roots[ai], item);
    }
    // exit(0);

    // print_all(roots, 5);

    int q; cin >> q;
    int ql, qr, qx, qy;
    Node *l, *m, *r;
    while(q--){
        cin >> ql >> qr >> qx >> qy;
        ql--;
        qr--;
        split(roots[qx], l, r, qr);
        split(l, l, m, ql - 1);
        merge(roots[qx], l, r);
        Union(roots[qy], roots[qy], m);
        // print_all(roots, 5);
    }

    vector<int> ans(n, -1);
    for(int i = 1; i <= 100; i++){
        dfs(roots[i], ans, i);
    }
    for(int i = 0; i < n; i++){
        cout << ans[i] << " ";
    }
    // dfs(t);
    cout << "\n";
    // cout << nop << "\n";
    
    return 0;
}
