// Template generated by Clank
#include<bits/stdc++.h>
using namespace std;
#define st first
#define nd second
#define all(x) x.begin(), x.end()
#define BOOST cin.tie(NULL); ios_base::sync_with_stdio(false);
// #define int ll
typedef long long ll;
using vi = vector<int>;

void sccdfs(int u, int c, vi &vis, vi &vstck, vector<vi> &g){
    vis[u] = c;
    for(int v : g[u])
        if(!vis[v])
            sccdfs(v, c, vis, vstck, g);
    vstck.push_back(u);
}
// everything is 1-indexed
// graph, reverse graph, graph of SCC, in what SCC is given vertex
int findSCC(int n, vector<vector<int>> &g, vector<vector<int>> &rg, vector<vector<int>> &SCC, vector<int> &SCCid){
    vector<int> order;
    vector<int> vis(n + 1, 0);
    for(int i = 1; i <= n; i++)
        if(!vis[i]) 
            sccdfs(i, i + 1, vis, order, g);
    for(int i = n; i >= 1; i--){
        if(!SCCid[order[i]]){
            SCC.emplace_back(); 
            sccdfs(order[i], SCC.size(), SCCid, SCC.back(), rg);
        }
    }
    return SCC.size();
}

int32_t main(){
    BOOST;
    int n, m; cin >> n >> m;
    vector<vi> g(n);   
    vector<vi> rg(n);
    int u,v;
    for(int i = 0; i < m; i++){
        cin >> u >> v;
        u++; v++;
        g[u].push_back(v);
        rg[v].push_back(u);
    }
    vector<vi> SCC;
    vi SCCid(n + 1);
    findSCC(n, g, rg, SCC, SCCid);
    cout << SCC.size();
    for(int i = 0; i < n; )
    return 0;
}
