// Template generated by Clank
#include<bits/stdc++.h>
using namespace std;
#define st first
#define nd second
#define all(x) x.begin(), x.end()
#define BOOST cin.tie(NULL); ios_base::sync_with_stdio(false);
// #define int ll
typedef long long ll;

struct Node{
    int p;
    int s = 1;
    int v;
    Node *l = NULL, *r = NULL;
    Node(int iv) : v(iv), p(rand()) {}
};

int gets(Node* t){
    return t ? t->s : 0;
}

void update(Node *t){
    if(t){
        t->s = gets(t->l) + 1 + gets(t->r);
    }
}

void split(Node *t, Node *&lt, Node *&rt, int pos){
    if(!t){
        lt = rt = NULL;
        return;
    }
    if(gets(t->l) < pos){
        split(t->r, t->r, rt, pos - gets(t->l) - 1);
        lt = t;
    } else {
        split(t->l, lt, t->l, pos);
        rt = t;
    }
    update(t);
}

void merge(Node *&t, Node *lt, Node *rt){
    if(!lt) {t = rt; return;}
    if(!rt) {t = lt; return;}
    if(lt->p > rt->p){
        merge(lt->r, lt->r, rt);
        t = lt;
    } else {
        merge(rt->l, lt, rt->l);
        t = rt;
    }
    update(t);
}

void dfs(Node *t){
    if(!t) return;
    dfs(t->l);
    cout << t->v << " ";
    dfs(t->r);
}

int32_t main(){
    BOOST;

    srand(42);

    int n; cin >> n;
    Node *t = NULL;
    Node *item;

    for(int i = 1; i <= n; i++){
        item = new Node(i);
        merge(t, t, item);
    }


    int a, b;
    Node *L, *R, *M, *A, *B;
    int len;
    for(int i = 0; i < n; i++){
        cin >> a >> b;
        if(a >= b) continue;
        len = min(n - b, b - 1 - a);
        split(t, t, B, b - 1);
        split(B, B, R, len + 1);
        split(t, L, A, a - 1);
        split(A, A, M, len + 1);

        merge(L, L, B);
        merge(M, M, A);
        merge(R, M, R);
        merge(t, L, R);
    }

    dfs(t);
    cout << "\n";
    return 0;
}
