// Template generated by Clank
#include<bits/stdc++.h>
using namespace std;
#define st first
#define nd second
#define all(x) x.begin(), x.end()
#define BOOST cin.tie(NULL); ios_base::sync_with_stdio(false);
// #define int ll
typedef long long ll;

struct Node{
    ll k, p;
    ll val;
    ll sum;
    Node *l, *r;

    Node(ll ik, ll ival) : k(ik), p(rand()), val(ival), sum(ival), l(NULL), r(NULL) {}
    void update();
};

ll gval(Node *t){ return t ? t->val : 0; }
ll gsum(Node *t){ return t ? t->sum : 0; }
void Node::update(){
    sum = val + gsum(l) + gsum(r);
}

void split(Node *t, Node *&lt, Node *&rt, ll split_key){
    if(!t){
        lt = rt = NULL;
    } else if(t->k <= split_key){
        split(t->r, t->r, rt, split_key);
        lt = t;
        lt->update();
    } else {
        split(t->l, lt, t->l, split_key);
        rt = t;
        rt->update();
    }
}

void merge(Node *&t, Node *lt, Node *rt){
    if(!lt){t = rt; return;}
    if(!rt){t = lt; return;}
    if(lt->p > rt->p){
        merge(lt->r, lt->r, rt);
        t = lt;
    } else {
        merge(rt->l, lt, rt->l);
        t = rt;
    }
    if(t) t->update();
}

void insert(Node *&t, Node *item){
    Node* lt, *rt;
    split(t, lt, rt, item->k);
    merge(lt, lt, item);
    merge(t, lt, rt);
}

ll sum_leq(Node *t, ll lim){
    if(!t) return 0;
    if(t->k <= lim){
        return gsum(t->l) + gval(t) + sum_leq(t->r, lim);
    } else {
        return sum_leq(t->l, lim);
    }
}

int32_t main(){
    BOOST;
    
    int n; cin >> n;
    
    Node *t = NULL;
    Node *item = NULL;

    ll u, v;
    ll L = 0;
    while(n--){
        cin >> u >> v;
        u ^= L;
        v ^= L;
        item = new Node(u, v);
        insert(t, item);
        L = sum_leq(t, u);
        cout << u << " " << L << "\n";
    }   

    return 0;
}
