// Template generated by Clank
#include<bits/stdc++.h>
using namespace std;
#define st first
#define nd second
#define all(x) x.begin(), x.end()
#define BOOST cin.tie(NULL); ios_base::sync_with_stdio(false);
// #define int ll
typedef long long ll;

 
int32_t main(){
    BOOST;
    int n; cin >> n;
    ll ans = 0;
    ll last; cin >> last;
    ll tmp;
    for(int i = 1; i < n; i++){
        cin >> tmp;
        ans += max(0LL, last - tmp);
        last = tmp + max(0LL, last - tmp);
    }
    cout << ans << "\n";
    return 0;
}
