// Template generated by Clank
#include<bits/stdc++.h>
using namespace std;
#define st first
#define nd second
#define all(x) x.begin(), x.end()
#define BOOST cin.tie(NULL); ios_base::sync_with_stdio(false);
// #define int ll
typedef long long ll;

 
int32_t main(){
    BOOST;
    int n; cin >> n;
    vector<int> x(n + 1);
    int tmp;
    for(int i = 0; i < n - 1; i++){
        cin >> tmp;
        x[tmp] = 1;
    }
    for(int i = 1; i <= n; i++){
        if(x[i]) continue;
        cout << i << "\n";
        break;
    }
    return 0;
}
