// Template generated by Clank
#include<bits/stdc++.h>
using namespace std;
#define st first
#define nd second
#define all(x) x.begin(), x.end()
#define BOOST cin.tie(NULL); ios_base::sync_with_stdio(false);
// #define int ll
typedef long long ll;

 
int32_t main(){
    BOOST;
    string s; cin >> s;
    s.push_back('X');
    int ans = 0, ctr = 1;
    for(int i = 1; i < s.size(); i++){
        if(s[i - 1] == s[i]) ctr++;
        else ctr = 1;
        ans = max(ans, ctr);
    }
    cout << ans << "\n";
    return 0;
}
