// Template generated by Clank
#include<bits/stdc++.h>
using namespace std;
#define st first
#define nd second
#define all(x) x.begin(), x.end()
#define BOOST cin.tie(NULL); ios_base::sync_with_stdio(false);
// #define int ll
typedef long long ll;

 
int32_t main(){
    // BOOST;
    ll n; cin >> n;
    while(n != 1){
        cout << n << " ";
        if(n&1){
            n = 3 * n + 1;
        } else {
            n /= 2;
        }
    }
    cout << n << "\n";
    return 0;
}
